### ISSUE TITLE
mac配置报错

### ISSUE THREAD

**Issue by phpmaple** [lhie1/Surge#1]
# MytvSUPER

DOMAIN-KEYWORD,nowtv100,🇨🇳 3⃣️ # hk
DOMAIN-KEYWORD,rthklive,🇨🇳 3⃣️ # hk
DOMAIN-SUFFIX,tvb.com,🇨🇳 3⃣️ # hk
DOMAIN-SUFFIX,mytvsuper.com,🇨🇳 3⃣️ # hk
DOMAIN-SUFFIX,qin.io,🇨🇳 3⃣️ # hk
IP-CIDR,202.126.56.114/24,🇨🇳 3⃣️ # hk,no-resolve

这段报错  🇨🇳 3⃣️ # hk貌似上面没有定义

**Comment by lhie1** [comment]
忘记删除了 已修改
