### ISSUE TITLE
IOS 淘宝客户端好多图片不显示

### ISSUE THREAD

**Issue by miniers** [lhie1/Surge#100]
大部分不是广告，都是商品图

**Comment by lhie1** [comment]
我测试并没有看到什么图片屏蔽

**Comment by miniers** [comment]
![unadjustednonraw_thumb_eff](https://user-images.githubusercontent.com/2039910/26962213-49788dcc-4d17-11e7-8a16-fa5b54865ec9.jpg)
![unadjustednonraw_thumb_f00](https://user-images.githubusercontent.com/2039910/26962219-51c29482-4d17-11e7-9b4d-b59ddb6f5bff.jpg)
![unadjustednonraw_thumb_f01](https://user-images.githubusercontent.com/2039910/26962221-58b6a292-4d17-11e7-8520-063254179d3e.jpg)

发生在删除重新安装淘宝后

**Comment by miniers** [comment]
好吧，再次测试是和 mitm 有关😂

**Comment by miniers** [comment]
主要是新生成的证书添加描述后没有设置为信任
