### ISSUE TITLE
shadowrocket配置文件，乐视视频HD，ipad版的开启后播放失败

### ISSUE THREAD

**Issue by menghany** [lhie1/Surge#101]
一直在加载，向下一个跳转

**Comment by lhie1** [comment]
有时间我测试了再看

**Comment by lhie1** [comment]
我用 Surge 测试一切正常（屏蔽广告、播放正常）

Shadowrocket.conf 与 Surge.conf 99.99%相似度 按理也应该一切正常

**Comment by menghany** [comment]
@lhie1 晚上回家我再测试一下 不行的话我试着录一个gif

**Comment by menghany** [comment]
不好意思，昨天工作原因没时间弄，已经上传gif图，图片可能比较大~麻烦查看
![2017-06-16 18_45_18](https://user-images.githubusercontent.com/13767186/27223700-33d3964e-52c4-11e7-8171-989c748fd879.gif)

**Comment by lhie1** [comment]
诶 可是我测试真没问题阿 都是最新的吗

证书方面呢

**Comment by menghany** [comment]
重新安装了证书，乐视我也卸载重装了~.不过我在手机端乐视试了一下是可以的

**Comment by lhie1** [comment]
很认真的回答：我这几天都测试了（我女朋友现在正在使用乐视视频 for iPad观看“深夜食堂”） 确实没有问题

**Comment by menghany** [comment]
多谢~,那我这边再把配置什么的重新试一下.
