### ISSUE TITLE
感谢大大的shadowrocket规则，有一个问题，这个规则没有域名转跳,在ios设置为中国，Safari 浏览器默认搜索引擎是谷歌的情况下，不能自动转跳到www.google.com不太方便，希望加入域名转跳。

### ISSUE THREAD

**Issue by artcaster** [lhie1/Surge#111]
感谢大大的shadowrocket规则，有一个问题，这个规则没有域名转跳,在ios设置为中国，Safari 浏览器默认搜索引擎是谷歌的情况下，不能自动转跳到www.google.com不太方便，希望加入域名转跳。

**Comment by lhie1** [comment]
有跳转阿..

**Comment by artcaster** [comment]
并没有吧,url重写部分是0，safari地址栏直接搜索没法用。

自己加上这个才能用

发自我的 iPad

**Comment by artcaster** [comment]
我说的是建议加入sr默认规则里面的
[URL Rewrite]
^http://(www.)?g.cn https://www.google.com header
^http://(www.)?google.cn https://www.google.com header
^http://reject.example.com reject

**Comment by lhie1** [comment]
你是直接用URL导入的？

你得看看用户手册 暂时不支持这个方式导入

使用 Workflow 导入吧

**Comment by artcaster** [comment]
我是添加配置导入的，这样不对吗？


发自我的 iPhone

**Comment by lhie1** [comment]
我的规则暂时不支持这样了
