### ISSUE TITLE
国泰君安君弘app启动三秒广告

### ISSUE THREAD

**Issue by meiyueyaxiao** [lhie1/Surge#113]
Surge

软件名称：国泰君安君弘
下载链接：https://itunes.apple.com/us/app/%E5%9B%BD%E6%B3%B0%E5%90%9B%E5%AE%89%E5%90%9B%E5%BC%98-%E5%9B%BD%E6%B3%B0%E5%90%9B%E5%AE%89%E8%AF%81%E5%88%B8app%E5%93%81%E7%89%8C%E5%85%A8%E6%96%B0%E5%8D%87%E7%BA%A7/id952047557?mt=8
问题描述：app启动三秒广告
感谢ihie1dalao

**Comment by lhie1** [comment]
👌
