### ISSUE TITLE
请求去除开屏广告 Surge

### ISSUE THREAD

**Issue by Six9od** [lhie1/Surge#115]
Surge
软件名称：来疯、咪咕直播
下载链接：来疯：https://itunes.apple.com/us/app/%E6%9D%A5%E7%96%AF/id904198248?mt=8
咪咕直播：https://itunes.apple.com/cn/app/%E5%92%AA%E5%92%95%E7%9B%B4%E6%92%AD/id1061810869?mt=8
问题描述：能否去除开屏广告，谢谢

**Comment by lhie1** [comment]
ok
