### ISSUE TITLE
请问能否添加追书小说的去广告规则？

### ISSUE THREAD

**Issue by gurenn** [lhie1/Surge#116]
一个是启动广告，另外一个是书架内的游戏推广，只找到了点击跳转Appstore的链接加以屏蔽。能否直接屏蔽游戏字条的推送？以前越狱时用flex实现过去广告。
追书小说-小说阅读听书追书神器 作者是 lian you
https://appsto.re/cn/nuaJ8.i

**Comment by gurenn** [comment]
例如我已找到疑似地址为http://api10e46r.zhuishushenqi.com/advert?platform=ios&position=all
添加关键词*advert*却并不能禁止加载成功。但是如果添加的是域名前面的变量又涉及到一些正常访问而且会api一变就失效了。这个该怎么修改？

**Comment by lhie1** [comment]
确定这是广告地址吧？

^https?://api10e46r.zhuishushenqi.com/advert - reject

**Comment by lhie1** [comment]
api 后面是否有“10e46r”

^https?://api.zhuishushenqi.com/advert - reject
^https?://api.zhuishushenqi.com/notification/shelfMessage - reject
^https?://api.zhuishushenqi.com/recommend - reject
^https?://api.zhuishushenqi.com/splashes/ios - reject
^https?://mi.gdt.qq.com/gdt_mview.fcg - reject

**Comment by lhie1** [comment]
一直都有屏蔽，卸载重装即可
