### ISSUE TITLE
希望支持自定义General和mitm中的hostname部分

### ISSUE THREAD

**Issue by miniers** [lhie1/Surge#118]
需要自定义代理的端口和dns之类，开发中也要用到一些mitm的解析，每次手动改好麻烦😂，谢谢啦

**Comment by lhie1** [comment]
这部分不太方便使用修改..

而且改动一下 User Data + Rule OTA 都需要作相应的调整

**Comment by miniers** [comment]
对的对的，前一段自己改了下workflow，结果你更新的太勤快了😂，每次在手机上修改好痛苦

**Comment by lhie1** [comment]
如果只是个人使用 修改起来应该听方便的
