### ISSUE TITLE
添加对Pixiv广告的过滤

### ISSUE THREAD

**Issue by quericy** [lhie1/Surge#12]
Pixiv客户端底部广告条严重影响使用感官,建议添加拒绝规则:
`DOMAIN-SUFFIX,d.socdm.com,REJECT`

另, e.qq.com的拒绝规则似乎会间歇导致其他应用内分享到QQ时,首次提示无网络连接(不确定)

**Comment by lhie1** [comment]
感谢提供

`DOMAIN-SUFFIX,d.socdm.com,REJECT` 已添加

`e.qq.com` 暂时未发现问题，会持续关注

**Comment by aiastia** [comment]
这个广告规则 添加 了 下面 还是有白条的吧……
