### ISSUE TITLE
刚接触，请教一下步骤。

### ISSUE THREAD

**Issue by mTerminal** [lhie1/Surge#120]
作者您好，我使用了workflow，首先我导入user data了，添加好自己的节点，运行，然后导入rule ota，选好自己需要的选项，再次运行，surge提示覆盖规则，这样是否就已经配置好了？当我二次启动surge的时候，我直接打开surge开关就可以了吧？还需要走一遍workflow的user data和rule ota吗？还是只要第一遍配置好之后，作者您有更新规则，我再去运行workflow呢？
问的问题比较初级，但确实是我的疑问，希望作者不吝赐教，谢谢。

**Comment by lhie1** [comment]
我好像回复了邮件 请问有收到吗

**Comment by mTerminal** [comment]
@lhie1  作者您好，我没有收到您的邮箱，请问你是发给了我么，我的邮箱：hmhoumeng@gmail.com

**Comment by lhie1** [comment]
我收到邮件直接就回复了，可能是 Github 的自动提示..

提示覆盖说明就已经导出成功，可以直接使用了。

如果只是更新规则 运行 Rule OTA 即可

可以在看看使用手册，两个流程分别负责哪些模块

**Comment by mTerminal** [comment]
@lhie1 多谢，我了解了。
当我全部流程都走完之后，如果我不进行一些配置的修改，我只需要打开surge点击运行就可以了吧？
因为workflow头一次用，不太熟悉，所以以为需要每次都要通过workflow运行一次，再通过surge运行。
😂多谢作者解惑，我将把问题关闭掉。

**Comment by lhie1** [comment]
记得安装并信任证书

**Comment by mTerminal** [comment]
@lhie1 多谢作者提醒，我会按照步骤正确配置。😄
