### ISSUE TITLE
add URL Rewrite

### ISSUE THREAD

**Issue by AnyoeDove** [lhie1/Surge#124]
// 快递100 kuaidi100 (MITM添加 p.kuaidi100.com, cdn.kuaidi100.com)
^(http|https)://qzonestyle.gtimg.cn/qzone/biz/gdt/mob/sdk/ios/v2/.* - reject
^(http|https)://cdn.kuaidi100.com/images/open/appads - reject
^(http|https)://p.kuaidi100.com/mobile/mainapi.do - reject

// 小米运动 MiFit (MITM添加 hm.xiaomi.com) 
^(http|https)://hm.xiaomi.com/.\*/app/startpages.json - reject //启动广告，需卸载重装
^(http|https)://hm.xiaomi.com/.\*/soc/well/list/community? - reject //状态页社区精选
^(http|https)://hm.xiaomi.com/discovery/mi/discovery/homepage_ad? - reject
^(http|https)://hm.xiaomi.com/discovery/mi/discovery/sport_ad? - reject

// Weico
^(http|https)://.\*/portal.php\\?a=get_ads.* - reject
^(http|https)://.\*/portal.php\\?c=duiba.* - reject 
^(http|https)://.\*/portal.php\\?a=get_coopen_ads.* - reject
^(http|https)://weicoapi.weico.cc/img/ad/.* - reject
^(http|https)://.\*/weico4ad/ad/.* - reject

// 超级星饭团 StarFans
^(http|https)://g.cdn.pengpengla.com/starfantuan/boot-screen-info/.* - reject //启动页广告图，去留随意

// 部分论坛
^(http|https)://discuz.gtimg.cn/cloud/scripts/discuz_tips.js - reject

//  某些果盘游戏内建广告
^(http|https)://sapi.guopan.cn/get_buildin_ad - reject

BTW, Hostname.conf 中 capi.douyucdn.com 应为 capi.douyucdn.cn

**Comment by lhie1** [comment]
非常感谢
