### ISSUE TITLE
添加提请

### ISSUE THREAD

**Issue by comedian555** [lhie1/Surge#125]
软件名称：和我信
下载链接：https://itunes.apple.com/cn/app/he-wo-xin/id1065421915?mt=8
问题描述：希望屏蔽开屏广告

**Comment by a3946** [comment]
软件名称：闲鱼
问题描述：去广告失效

**Comment by a3946** [comment]
软件名称：京东金融，艺龙旅行
问题描述：希望开启您有时间去下两个APP广告

**Comment by hl120508** [comment]
软件名称：动漫之家、PicACG
问题描述：动漫之家开屏广告  DOMAIN-SUFFIX,shuttle.bayescom.com,REJECT
                   PicACG应用内广告 DOMAIN-SUFFIX,juicyads.com,REJECT

**Comment by AnyoeDove** [comment]
@a3946 你的设备是5s或者SE吧，屏幕分辨率是640x1136所以规则没有匹配上，添加下面两条规则
^(http|https)://gw.alicdn.com/tfs/.*640-1136.* - reject
^(http|https)://gw.alicdn.com/tps/.*640-1136.* - reject
@lhie1

**Comment by a3946** [comment]
不啊 我的设备是7

**Comment by AnyoeDove** [comment]
@a3946 那请详细阅读README中的Q&A部分

**Comment by 8vo** [comment]
软件名称：nga玩家社区
下载链接：https://at.umeng.com/TbKLny
问题描述：开启app的启动广告和帖子之间的广告
谢谢

**Comment by lhie1** [comment]
和我信那个不是启动广告，软件自带的启动画面无法去除

**Comment by lhie1** [comment]
NGA玩家社区无法启动（闪退）
