### ISSUE TITLE
广告屏蔽

### ISSUE THREAD

**Issue by Mijjj** [lhie1/Surge#128]
驾考宝典-2017最新考驾照驾校学车驾考通 作者是 jiang yinghao
https://appsto.re/cn/LRWHE.i

**Comment by AnyoeDove** [comment]
// 驾考宝典 (MITM添加：*.789.kakamobi.cn) 卸载重装
^(http|https)://.\*789.kakamobi.cn/.\*adver.\* - reject
^(http|https)://smart.789.image.mucang.cn/advert.\* - reject

**Comment by lhie1** [comment]
多谢提供

顺便说一下：https? 的正则的匹配效率是优于 (http|https) 的
