### ISSUE TITLE
shadowrocket使用workflow更新的规则后微信链接走的是代理,且无法收发消息

### ISSUE THREAD

**Issue by menghany** [lhie1/Surge#129]
日志如截图,wifi下正常,联通4G不行

![img_3512](https://user-images.githubusercontent.com/13767186/28665336-f090d4c6-72f5-11e7-8b0f-e211632074dc.PNG)

**Comment by lhie1** [comment]
我检查脚本并重新生成 没发现这个问题

**Comment by lhie1** [comment]
AuthKey

建议仔细阅读“使用手册”

**Comment by menghany** [comment]
感谢
