### ISSUE TITLE
outlook app接收邮件问题

### ISSUE THREAD

**Issue by ysneo** [lhie1/Surge#13]
开了代理新邮件加载不出，关掉vpn 立马就刷出邮件了

**Comment by lhie1** [comment]
不好意思才看到，是 iOS 系统吗？

**Comment by ysneo** [comment]
可能我线路有点问题，sr
lhie1 <notifications@github.com>于2017年1月13日 周五16:57写道：

**Comment by lhie1** [comment]
好的..
