### ISSUE TITLE
屏蔽直播吧app的广告

### ISSUE THREAD

**Issue by nghsiang** [lhie1/Surge#130]
格式如下：

Surge / Shadowrocket

软件名称：直播吧
下载链接：直播吧(官方版)-体育从这里开始 作者是 ZHIBO8
https://appsto.re/cn/3h5yH.i
问题描述：app中的的新闻夹杂着各种京东浏览过的商品的广告等广告

**Comment by lhie1** [comment]
直播吧的启动广告一直都有被拦截

我没有看到夹杂的京东广告 请尝试卸载重装且不要在代理关闭的时候运行此app

**Comment by nghsiang** [comment]
卸载重装貌似有效！

2017年8月5日 +0800 19:06 lhie1 <notifications@github.com>，写道：
