### ISSUE TITLE
关于steam。

### ISSUE THREAD

**Issue by mTerminal** [lhie1/Surge#135]
作者您好，surge for mac，用您的规则发现，steam商店走的是代理，因为价格显示都是外币，还要进行换算人民币，但是真正下载游戏的时候通过surge dashboard看到steam走的又是直连，请问是规则对steam做了处理吗？

**Comment by lhie1** [comment]
你可以在 dashboard 看到是哪一条规则影响了 steam

好像没有对 steam 进行控制

**Comment by mTerminal** [comment]
@lhie1 您好，我不是太懂，看到 policy 那里显示 HK(FINAL)，

**Comment by mTerminal** [comment]
@lhie1 我现在通过添加一条自定义，把 steam 的链接归为 cn 链接，强制直连，可以解决，但是规则我使用的 icloud，手机端 workflow rule ota 更新之后，还要重新添加吧？

**Comment by lhie1** [comment]
因为我的规则没有对 steam 进行控制，Surge根据ip库自动将它设为代理，steam 可以直连么？我记得有墙

**Comment by mTerminal** [comment]
@lhie1 可以打开，关闭所有代理，确实能打开，我先暂时把他设置直连吧。

**Comment by lhie1** [comment]
如果你保证直连可用 可以将地址提交给我 我合并进去 谢谢

**Comment by mTerminal** [comment]
@lhie1 退出surge 和 shadowsocks-ng 之后，确实可以打开 steam 商店官网。
网址为：`store.steampowered.com` 。

**Comment by lhie1** [comment]
好的 已合并

**Comment by mTerminal** [comment]
@lhie1  好的，多谢，我去更新一下，已经并入 rute ota 了吗？

**Comment by lhie1** [comment]
是的

**Comment by mTerminal** [comment]
@lhie1 好的，多谢作者大大。
我将把问题关闭。
