### ISSUE TITLE
集享联盟app（全家）无法加载，修改crt.comodo....就OK了

### ISSUE THREAD

**Issue by zero2sin** [lhie1/Surge#139]
comodo的证书应该还是业内比较信任的高端证书吧，为什么reject呢，麻烦看下是不是该修改，每次更新wf后就用不了全家，还得自己修改.....

**Comment by lhie1** [comment]
@zero2sin 不知道

**Comment by xavierzz** [comment]
@lhie1 这个是在YouTube的规则里面的，不过我已经去掉了，不去掉会看到好多他的reject，去了不影响使用，YouTube也一样没广告。我也觉得没必要屏蔽这个crt。

**Comment by lhie1** [comment]
@xavierzz 刚刚在测试 bot 最新规则已移除..
