### ISSUE TITLE
notion.so 服务器超时

### ISSUE THREAD

**Issue by Aixtuz** [lhie1/Surge#142]
首次登录 notion 时无法打开谷歌账户授权页面，
完全退出后重开，提示：
```
The server is taking longer than expected to respond.
```

尝试过如下操作：
- 关闭一次 surge 后，待 app 内容正常显示，之后再打开 surge 访问文档无影响。
- 注释掉 notion.so 该行无效果，但换几个月前的配置文件一切正常。

**Comment by lhie1** [comment]
@Aixtuz

**Comment by lhie1** [comment]
我测试一切正常..
