### ISSUE TITLE
workflow authkey 获取上的疑问

### ISSUE THREAD

**Issue by HZH1907** [lhie1/Surge#143]
首先感谢大大提供的workflow，在此基础上获取和自定义规则变得很简单。

使用了大半个月，随着对workflow的了解，渐渐理解了各个流程的含义。于是产生了使用上的问题。

我的authkey一开始是无法获取的，我在url-rewrite里面看到authkey后面什么都没有，然后我研究了一下认为这个流程说的运行两遍以便key正确获取的意思是运行第一遍得到的conf 在surge里开启后 运行第二遍async.be 和ip.cn才会走代理，然后获得对应代理ip的authkey，问题就出在第二遍的时候，会出现MITM的错误，也就是https://github.com/lhie1/Surge#workflow_qa 里证书效验失败的问题，然后workflow不会继续运行，而MITM证书已经正确安装并且信任。

如果不开启surge，async.be 和ip.cn不会走代理，获得的key就不对了呀，复检也不对。然后我看到https解密里有async.be，我之前用MITM出现过因为这个https证书的问题workflow不跑的情况，于是我删掉了MITM里async.be的主机名，后面authkey就正确获取了，似乎workflow运行的时候并不能那个开启async.be的https解密，后续url-rewrite的使用过程中是否需要MITM，我也不懂......

我是小白，说话还啰嗦，望大大指教。

**Comment by lhie1** [comment]
你所说的问题是因为你安装了证书却没有信任证书（关于本机）

现在绝大部分app广告不能直接通过DOMAIN直接拦截或屏蔽

所以需要 Url Rewrite 达到更精确的拦截（大多数需要依赖mitm，而且很麻烦很繁琐，我必须要下载app，并打开试用再逐一分析）

**Comment by HZH1907** [comment]
啊！！！原来如此！！！

surge里面的系统已信任，和关于本机里的信任并不一样啊。我还以为我已经信任了证书了呢.....

好的，谢谢大大，承蒙指教，不胜荣幸~~

**Comment by lhie1** [comment]
@HZH1907 不客气
