### ISSUE TITLE
规则更新到version20后优酷6.9.4去广告失败

### ISSUE THREAD

**Issue by sagexy** [lhie1/Surge#145]
今天更新规则到version20后打开优酷6.9.4过滤广告失败，但是降到优酷6.9.2之后可以正常过滤广告，VIP播放正常，难道是我的打开方式不对么？请大大确认！
![img_0321](https://user-images.githubusercontent.com/4734448/29547484-cd825e50-872c-11e7-963a-101f6cdf748c.PNG)
![img_0322](https://user-images.githubusercontent.com/4734448/29547485-cd9e3670-872c-11e7-808f-61bc118b874c.PNG)
![img_0324](https://user-images.githubusercontent.com/4734448/29547486-cdc5791a-872c-11e7-9630-55bfc2d27016.PNG)
![img_0325](https://user-images.githubusercontent.com/4734448/29547487-cdd21cb0-872c-11e7-9c00-62391295faf1.PNG)

**Comment by lhie1** [comment]
@sagexy 不是说了已经失效了吗

**Comment by sagexy** [comment]
@lhie1 sorry 我没有留到哪里提到失效了

**Comment by lhie1** [comment]
@sagexy tg 频道里说了..
