### ISSUE TITLE
想问问surge的规则优先级

### ISSUE THREAD

**Issue by VinkenCheng** [lhie1/Surge#148]
你好，我想问问如果某个url同时命中多个规则，那么是采用哪个规则呢？也就是说规则的优先级是从上到下的还是按照某种规律（如: DOMAIN->DOMAIN-SUFFIX->DOMAIN-KEYWORD）？

举个栗子：
surge_lite的规则中，我看Dashboard，app.smartmailcloud.com这url走的是Proxy呢，这样看起来是按从上到下的顺序匹配，那规则中的排序有很重要了

**Comment by lhie1** [comment]
@VinkenCheng 是的 从上往下

**Comment by VinkenCheng** [comment]
@lhie1 好的，谢谢。从上往下的话，那规则顺序就需要重排一下了，类似DOMAIN->DOMAIN-SUFFIX->DOMAIN-KEYWORD，REJECT->DIRECT->Proxy

**Comment by lhie1** [comment]
@VinkenCheng 我一直都很注重这个问题 尽管用吧

**Comment by VinkenCheng** [comment]
PROCESS-NAME,HazeOver,REJECT
PROCESS-NAME,IP Scanner,REJECT
PROCESS-NAME,trustd,Apple
USER-AGENT,AdBlock*,Domestic
DOMAIN,valf.atm.youku.com,Domestic
DOMAIN,gist.github.com,Proxy
DOMAIN-SUFFIX,apache.org,Domestic
DOMAIN-SUFFIX,beatsbydre.com,Domestic
DOMAIN-SUFFIX,eclipse.org,Domestic
DOMAIN-SUFFIX,github.com,Domestic
DOMAIN-SUFFIX,jd.hk,Domestic
DOMAIN-SUFFIX,maven.org,Domestic
DOMAIN-SUFFIX,nssurge.com,Domestic
DOMAIN-SUFFIX,paypal.com,Domestic
DOMAIN-SUFFIX,pgyer.com,Domestic
DOMAIN-SUFFIX,symcd.com,Domestic
DOMAIN-SUFFIX,trello.com,Domestic
DOMAIN-SUFFIX,trellocdn.com,Domestic
DOMAIN-SUFFIX,ttmeiju.com,Domestic
DOMAIN-SUFFIX,vultr.com,Domestic
DOMAIN-SUFFIX,xclient.info,Domestic
DOMAIN-SUFFIX,mxhichina.com,Domestic  // imap & smtp
DOMAIN-SUFFIX,exmail.qq.com,Domestic  // imap & smtp
DOMAIN-SUFFIX,fixsub.com,Proxy
DOMAIN-SUFFIX,gpx-poi.com,Proxy
DOMAIN-SUFFIX,ip.cn,use4test
DOMAIN-SUFFIX,ipip.net,use4test
DOMAIN-SUFFIX,ipinfo.io,use4test
DOMAIN-SUFFIX,speedsmart.net,use4test
DOMAIN-SUFFIX,speedtest.net,use4test
PROCESS-NAME,Speedtest,use4test
USER-AGENT,Speedtest*,use4test
// Custom UA
// USER-AGENT,Royal*,Domestic
USER-AGENT,cmblife*,Domestic
PROCESS-NAME,Paws for Trello,Domestic
PROCESS-NAME,node-webkit,Proxy
IP-CIDR,106.75.65.90/32,REJECT,no-resolve

以上是我自己添加的规则，顺便贡献出来吧。有时间帮你的规则排一排序，理论优先级应该按DOMAIN->DOMAIN-SUFFIX->DOMAIN-KEYWORD这样来会好一点。

**Comment by lhie1** [comment]
@VinkenCheng 好的 谢谢

**Comment by VinkenCheng** [comment]
@lhie1 不客气，我也是用起来总感觉有些url走的规则怪怪的，该走Direct的结果走了Proxy，所以上来问一下的

**Comment by VinkenCheng** [comment]
还有两条，之前一直在用tokyo的服务器+google.hk所以强制改成这样的
^https?://(www.)?google\.(com|[a-z]{2})(\.[a-z]{2})? https://www.google.com.hk 302
^https?://youtube.com https://youtube.com/?gl=HK/ 302

**Comment by lhie1** [comment]
@VinkenCheng 这个就不加了 以免影响大家的体验 不过很感谢提供此方法

**Comment by VinkenCheng** [comment]
@lhie1 这个只是写个实例给有需要的人改，我是比较喜欢用google.com.hk的，广州连接速度最快

**Comment by VinkenCheng** [comment]
@lhie1 刚才稍微修改了一下顺序，参考：https://github.com/VinkenCheng/Surge_copy_from_lhie1

**Comment by lhie1** [comment]
@VinkenCheng 回家用电脑看看
