### ISSUE TITLE
Shadworocket 的apple proxy 可选策略建议

### ISSUE THREAD

**Issue by jackie0** [lhie1/Surge#154]
辛苦一天，感谢您的付出
本来正准备提issue的。结果有人先了，现在shadowrocket的apple proxy节点可选功能非常实用
但是没想到去掉了PROXY选项，PROXY还是很有用的，比如以下场景：
运行WorkFlow指定一个节点后，使用中该节点突然GG，那就需要再运行一次WorkFlow来重新选择其他节点才能访问apple；
如果有proxy选项，就可以有效避免这种情况，只需要在APP内切换另一个节点就OK
所以：最佳情况应该是有 DIRECT   PROXY   节点     
再次向您道谢

**Comment by lhie1** [comment]
@jackie0 最新的 Rule OTA 已经有了
