### ISSUE TITLE
JD

### ISSUE THREAD

**Issue by Yinrui** [lhie1/Surge#161]
最近几次的规则 导致jd除了首页之外的界面加载很慢，surge分析里面显示请求未完成，但是确实是走的直连的规则

**Comment by yinws** [comment]
@Yinrui 使用圈表示京东没加载问题

**Comment by Yinrui** [comment]
就是大佬在wf中加上圈之后的规则才出现的这个问题
yinws <notifications@github.com>于2017年8月31日 周四09:09写道：

**Comment by shigalin** [comment]
你是用圈的？

**Comment by Yinrui** [comment]
不是。用的surge。我是用surge分析的请求未完成
shiga <notifications@github.com>于2017年8月31日 周四09:11写道：

**Comment by shigalin** [comment]
我不是跑wf，直接用的配置文件的规则木有问题。你可以先试试，https://raw.githubusercontent.com/lhie1/Surge/master/Surge.conf

**Comment by Yinrui** [comment]
好的 我试试。谢谢
shiga <notifications@github.com>于2017年8月31日 周四09:14写道：

**Comment by Yinrui** [comment]
似乎不是屏蔽广告规则的问题。用链接也不行。我用wf跑不加任何广告的规则也打不开（900多条的）但是关闭surge就可以正常打开
蜂巢 <yinrui0508@gmail.com>于2017年8月31日 周四09:15写道：

**Comment by shigalin** [comment]
你是个例吧，重启手机试试吧。

**Comment by Yinrui** [comment]
试过了😂 重启大法是一开始就要用的 我也很奇怪
shiga <notifications@github.com>于2017年8月31日 周四09:24写道：

**Comment by Yinrui** [comment]
我用cloudgate的规则就可以正常打开
蜂巢 <yinrui0508@gmail.com>于2017年8月31日 周四09:25写道：

**Comment by AnyoeDove** [comment]
DNS的问题

**Comment by Yinrui** [comment]
应该不是吧 用的不是路由器上的dns么
Anyoe <notifications@github.com>于2017年9月1日 周五00:03写道：

**Comment by Rhysn** [comment]
是不是忘记在系统设置里启用CA证书了？

**Comment by lhie1** [comment]
京东没有任何问题（就算有问题我也会第一时间发现 我很喜欢用京东）
