### ISSUE TITLE
腾讯手机关机启动广告

### ISSUE THREAD

**Issue by debiansid** [lhie1/Surge#162]
怎么屏蔽？
ps
adcast.fblife.com reject导致手机浏览器无法访问bbs.fblife.com

**Comment by unknowntokyo** [comment]
腾讯手机管家这个好像是和归属地数据更新打包在一起的……🤦🏻‍♂️

**Comment by lhie1** [comment]
什么东西？
我测试`bbs.fblife.com`可以正常打开
