### ISSUE TITLE
关于规则重复的疑问

### ISSUE THREAD

**Issue by VinkenCheng** [lhie1/Surge#166]
哈哈我又要问个问题，关于规则重复的

比如Rule_REJECT里面118和120行
```
DOMAIN-SUFFIX,aiseet.atianqi.com,REJECT
...
DOMAIN-SUFFIX,dp3.play.aiseet.atianqi.com,REJECT
```

这两行应该是算重复吧？
DOMAIN-SUFFIX,aiseet.atianqi.com,REJECT这行规则理论上应该是包含了DOMAIN-SUFFIX,dp3.play.aiseet.atianqi.com,REJECT这个规则的

**Comment by lhie1** [comment]
@VinkenCheng 这属于重复了 应该删除

**Comment by VinkenCheng** [comment]
@lhie1 这就大工程了。。

**Comment by lhie1** [comment]
@VinkenCheng 慢慢来..

**Comment by VinkenCheng** [comment]
还是找个时间写个脚本出来自动清除重复规则好了

**Comment by VinkenCheng** [comment]
对了，Rule_reject和Url_reject会存在重复规则吗？
例如：
DOMAIN-SUFFIX,ark.letv.com,REJECT
和
^https?://ark.letv.com/adx\?adzone= - reject
这两个规则同时存在时

**Comment by lhie1** [comment]
@VinkenCheng 这个也属于重复了..

**Comment by VinkenCheng** [comment]
啊哈哈哈哈工程更大了
