### ISSUE TITLE
可以把这条规则加上, 这样旧版本追书的升级提示就没有了

### ISSUE THREAD

**Issue by XinSSS** [lhie1/Surge#167]
这个是surge的
URL-REGEX,^http://itunes.apple.com/lookup\?id=575826903,REJECT

小火箭,quan同样根据这个URL加规则就行
^http://itunes.apple.com/lookup\?id=575826903

因为是固定访问这个URL, 所以也没加https匹配, 这个不多不少

**Comment by XinSSS** [comment]
surge也还是重定向吧
^http://itunes.apple.com/lookup\?id=575826903 - reject

**Comment by lhie1** [comment]
@XinSSS 好的 谢谢
