### ISSUE TITLE
新版优酷开屏广告以及视频广告无法屏蔽

### ISSUE THREAD

**Issue by Six9od** [lhie1/Surge#177]
优酷开屏广告以及视频广告无法屏蔽
熊猫直播开屏广告无法屏蔽
希望能够增加。。谢谢

**Comment by Jumeo7** [comment]
@Six9od 熊猫直播：
^https://static.api.m.panda.tv/index.php\?method=clientconf.firstscreen - reject

**Comment by lhie1** [comment]
优酷早就放弃了
