### ISSUE TITLE
微医开屏广告望屏蔽

### ISSUE THREAD

**Issue by Six9od** [lhie1/Surge#178]
微医（挂号网）-在线挂号问诊平台 by Guahao(Hangzhou)Technology Co., Ltd.
https://itunes.apple.com/us/app/%E5%BE%AE%E5%8C%BB-%E6%8C%82%E5%8F%B7%E7%BD%91-%E5%9C%A8%E7%BA%BF%E6%8C%82%E5%8F%B7%E9%97%AE%E8%AF%8A%E5%B9%B3%E5%8F%B0/id595277934?mt=8
非常感谢

**Comment by lhie1** [comment]
Done.
