### ISSUE TITLE
大佬能否屏蔽健康160，车来了，壹钱包的开屏广告？

### ISSUE THREAD

**Issue by scyrte** [lhie1/Surge#185]
健康160：https://itunes.apple.com/hk/app/%E5%81%A5%E5%BA%B7160-%E5%B0%B1%E5%8C%BB160-%E6%8C%82%E5%8F%B7%E9%97%AE%E8%AF%8A%E8%B4%AD%E8%8D%AF%E5%81%A5%E5%BA%B7%E6%9C%8D%E5%8A%A1%E5%B9%B3%E5%8F%B0/id593811445?l=zh&mt=8

车来了：https://itunes.apple.com/us/app/%E8%BD%A6%E6%9D%A5%E4%BA%86-%E7%B2%BE%E5%87%86%E7%9A%84%E5%AE%9E%E6%97%B6%E6%8E%8C%E4%B8%8A%E5%85%AC%E4%BA%A4%E5%9C%B0%E9%93%81/id667831823?mt=8

壹钱包：https://itunes.apple.com/cn/app/%E5%A3%B9%E9%92%B1%E5%8C%85/id745097904?mt=8

**Comment by lhie1** [comment]
Done.
