### ISSUE TITLE
12306付款闪退。

### ISSUE THREAD

**Issue by microxiao** [lhie1/Surge#187]
shadowrocket 配置lhie1规则之后，12306付款闪退。

**Comment by lhie1** [comment]
@microxiao Surge 和 12306 不兼容

https://trello.com/c/Jsf9jq5R/32-已确认和-surge-有兼容性问题的-app

**Comment by lhie1** [comment]
虽然 Surge 和 Shadowrocket 不是同一个应用，意思应该差不多
