### ISSUE TITLE
关于知乎

### ISSUE THREAD

**Issue by microxiao** [lhie1/Surge#190]
实测使用lhie1的shadowrocket的规则，知乎客户端或者网页端，很多图片会加载不出来，可能跟几条regect规则有关

**Comment by lhie1** [comment]
@microxiao 因为证书

**Comment by microxiao** [comment]
好像是的，我删除了那几个规则，结果还是有部分图片加载不出来

**Comment by lhie1** [comment]
但是我说的是证书，和规则没关系
