### ISSUE TITLE
手机端游民星空无法浏览 开启 https解密后 掌上生活和豆瓣的图片 无法打开

### ISSUE THREAD

**Issue by z4jst** [lhie1/Surge#192]
游民星空 
ja.gamersky.com
ja1.gamersky.com

打开https解密后
用wf 获取豆瓣电影信息会提示 证书问题
相关条目
img3.doubanio.com

招行掌上生活
无法打开
相关条目
mlife.cmbchina.com

以上条目删去后 软件恢复正常

**Comment by Jumeo7** [comment]
@z4jst 开启解密的同时要安装并信任证书

**Comment by z4jst** [comment]
@Jumeo7 你好 我是开过而且在通用里面信任过的

**Comment by z4jst** [comment]
你好 我刚刚把之前的证书删掉 然后生成了信的证书之后（原来的证书号是surge正在用的的证书没问题，不知道为什么不行），现在可以用了。谢谢。

**Comment by z4jst** [comment]
更新过后，使用相同证书 或者 重建证书，还是不行。给跪了

**Comment by Jumeo7** [comment]
@z4jst 将可以正常使用的证书从文本模式中复制出来，粘贴到 User Data 中相应的部分，并从 User Data 开始运行一次。这样以后更新规则的时候就不会改变你的证书了。

**Comment by giveup** [comment]
有两个地方需要设置信任，第一是 Profiles 里，第二是关于拉到底部 Certificate Trust Settings，打开需要信任的证书。

**Comment by z4jst** [comment]
谢谢！@giveup 原来我没有信任关于里面的设置！！！现在ok 了
