### ISSUE TITLE
防骚扰大师在规则下，无法更新骚扰号码。

### ISSUE THREAD

**Issue by NathenHouse** [lhie1/Surge#200]
显示 无法联网，请检查网络是否流畅。关闭规则后缓解。360旗下的软件。

PS：因为号码同时收到浙江和天津的骚扰电话袭扰，而这类软件大部分都是加强一个地域，所以和QQ管家双开，不知道还有没有更聪明的办法。

**Comment by giveup** [comment]
什么App,查看log页面的reject,带有360字眼的添加到白名单.

**Comment by lhie1** [comment]
360 以前是屏蔽掉了，前两天解除了
