### ISSUE TITLE
百度地图不能正常使用

### ISSUE THREAD

**Issue by luyuqiang** [lhie1/Surge#201]
作者你好：
请问一下为什么使用了surge.conf的配置后，[百度地图](http://map.baidu.com)可以正常访问，可以看到地图。但是不能正常输入地址进行搜索。先开始还以为是ca证书的问题，一看百度地图并不是https。

**Comment by kevinzfjiang** [comment]
是无法调出输入法？
还是输入中文等字符却无法显示结果？
如果是第一个问题，那九成是第三方输入法的锅。重启手机可以解决。

**Comment by luyuqiang** [comment]
我可能没说明白，百度地图留的是pc端的网址，我指的是pc端的

**Comment by luyuqiang** [comment]
我已经解决了，原因是有一条过滤规则刚刚好匹配百度地图pc端的一个js，导致功能出现问题。
过滤规则： **[^.+ad(s|v)?.js - reject]**
百度地图pc端js：**[http://webmap1.map.bdstatic.com/wolfman/static/common/widget/route/setMyPlace/ui3SetMyPlacePop_83e74ad.js]**

**Comment by lhie1** [comment]
已解决
