### ISSUE TITLE
威锋网论坛加载缓慢 老刷不出来

### ISSUE THREAD

**Issue by lvhe19880210** [lhie1/Surge#203]
如题 新闻页面还好点论坛页面尤其严重
![c9cbffad-f0d5-4a1d-bcd7-bd9e82789b89](https://user-images.githubusercontent.com/29178968/30893302-095c0142-a370-11e7-92c3-db73af1b2b1b.jpeg)

**Comment by lhie1** [comment]
证书

**Comment by lvhe19880210** [comment]
@lhie1 证书有按了一次 还是不行

**Comment by lvhe19880210** [comment]
证书安装正确 但还是加载困难 不止我一个人

**Comment by lhie1** [comment]
我会好好检查一下
