### ISSUE TITLE
抖音视频确实无法播放，证书我也早就安装了。。。

### ISSUE THREAD

**Issue by BeliefanX** [lhie1/Surge#204]
抖音视频确实无法播放，证书我也早就安装了。。。
我用其它的规则，抖音是正常的，换了这个配置文件之后，就不能播放了。。。
我也通过看最近的请求记录，尝试修改规则，但都没有成功。。。
我用的是最新版的surge，version2.7.0。

**Comment by lhie1** [comment]
因为我屏蔽了抖音的启动广告，去认真阅读使用手册关于证书的描述

**Comment by BeliefanX** [comment]
我又去看了一遍使用手册，关于证书的部分，只显示的怎么安装，无论是Mac还是iphone我的证书都安好了，我刚才把抖音卸了重装了一遍，里面完全没有内容了～
telegram里面，我也找了相关信息，都没有找到怎么解决～
我也不知道问题出哪了。。。

**Comment by lhie1** [comment]
@BeliefanX 信任了吗？

**Comment by BeliefanX** [comment]
信任了啊，Iphone还有mac上，在surge里都显示系统已信任。。。
