### ISSUE TITLE
反馈一个网站CSS无法正常加载的问题

### ISSUE THREAD

**Issue by awe123343** [lhie1/Surge#206]
https://usa.visa.com/support/consumer/travel-support/exchange-rate-calculator.html
该网页无法正常加载，疑似与googletagmanager.com adnxs.com有关，如果方便的话麻烦修改下吧？谢lhie

**Comment by lhie1** [comment]
电脑端么？我用手机打开没有问题

**Comment by awe123343** [comment]
是电脑端，我再看看是不是我改了哪里导致的吧

**Comment by lhie1** [comment]
手机以及电脑测试都正常
