### ISSUE TITLE
多看阅读无法打开云空间

### ISSUE THREAD

**Issue by Artwalk** [lhie1/Surge#21]
`DOMAIN,sfsapi.micloud.xiaomi.net,REJECT` 

有办法跳过子路径包含 `.../duokan/...` 的规则吗？

**Comment by lhie1** [comment]
不太理解你的意思

**Comment by Artwalk** [comment]
就是说只有 sfsapi.micloud.xiaomi.net/*/duokan/*, direct
其他的 reject

我看 surge 好像是没法实现这种规则？

另外这个是为了 reject 小米的什么服务？

**Comment by lhie1** [comment]
Surge 暂时不支持

突然一下子问我这个是屏蔽什么.. 我也记不住

**Comment by lhie1** [comment]
下个版本可以了..

**Comment by Artwalk** [comment]
是指 Surge 的下个版本就支持这样的规则了？

**Comment by lhie1** [comment]
是的

**Comment by lhie1** [comment]
已修复
