### ISSUE TITLE
请求屏蔽同花顺、建设银行、饿了么开屏广告

### ISSUE THREAD

**Issue by Six9od** [lhie1/Surge#210]
同花顺-炒股、股票 by Zhejiang Hexin Flush Network Services Ltd
https://itunes.apple.com/us/app/%E5%90%8C%E8%8A%B1%E9%A1%BA-%E7%82%92%E8%82%A1-%E8%82%A1%E7%A5%A8/id303191318?mt=8

同花顺至尊版 by Zhejiang Hexin Flush Network Services Ltd
https://itunes.apple.com/us/app/%E5%90%8C%E8%8A%B1%E9%A1%BA%E8%87%B3%E5%B0%8A%E7%89%88/id954724812?mt=8

中国建设银行 by 中国建设银行
https://itunes.apple.com/us/app/%E4%B8%AD%E5%9B%BD%E5%BB%BA%E8%AE%BE%E9%93%B6%E8%A1%8C/id391965015?mt=8

**Comment by lhie1** [comment]
@Six9od 卸载重装
