### ISSUE TITLE
请问精简版有哪些功能？

### ISSUE THREAD

**Issue by reaCodes** [lhie1/Surge#212]
请问精简版有哪些功能？

是什么代理模式？我注意到国外的网站似乎无论有没有被墙，都走了代理，那这个代理规则是代理所有的国外IP地址吗？

如果不是，那是什么样的规则？

**Comment by lhie1** [comment]
精简版和完整版几乎一样，缺少可定制性（使用手册说了）

我没有加入 GFWList ，所以绝大部分的国外网站都是默认走代理

**Comment by giveup** [comment]
此项目的规则是广告屏蔽+白名单(GEOIP CN+常见国内App)+黑名单+默认代理。
所以不太适合按流量计费的服务器。
如阁下不嫌弃，可参考在下的规则。
广告屏蔽+黑名单+默认直连
https://github.com/giveup/Surge/blob/master/AD_GFW_Direct.conf

**Comment by lhie1** [comment]
好的 我看看

**Comment by lhie1** [comment]
我的规则大部分用在广告屏蔽上，除部分主流网站，其他均借助 GEOIP 进行分流，原因有两点（我不想把 GFWList 导入规则，太过臃肿；个人维护起来相当麻烦）

访问网页对流量的消耗微乎其微

因此我还是建议使用默认代理（也就是现在的模式）
