### ISSUE TITLE
大佬希望能屏蔽火猫TV和ofo的广告，万分感谢！

### ISSUE THREAD

**Issue by civilians** [lhie1/Surge#217]
火猫TV
火猫-热门竞技游戏直播平台 来自 WUXI QIAOXI CULTURE MEDIA CO.,LTD
https://itunes.apple.com/cn/app/%E7%81%AB%E7%8C%AB-%E7%83%AD%E9%97%A8%E7%AB%9E%E6%8A%80%E6%B8%B8%E6%88%8F%E7%9B%B4%E6%92%AD%E5%B9%B3%E5%8F%B0/id966104279?mt=8
ofo
ofo共享单车-小黄车1元包月 来自 Bikelock Technology CO., Ltd.
https://itunes.apple.com/cn/app/ofo%E5%85%B1%E4%BA%AB%E5%8D%95%E8%BD%A6-%E5%B0%8F%E9%BB%84%E8%BD%A61%E5%85%83%E5%8C%85%E6%9C%88/id1056015676?mt=8

**Comment by lhie1** [comment]
ofo 在美区无法下载，所以有人能帮忙抓就抓吧～
