### ISSUE TITLE
希望添加youtube的制定节点

### ISSUE THREAD

**Issue by idenpa** [lhie1/Surge#219]
希望能在workflow里添加一个youtube单独选择节点的选项，因为youtube很多视频会有区域限制，谢谢。

**Comment by Jumeo7** [comment]
@idenpa 爱奇艺只删除 IP-CIDR 部分的规则是 Workflow 里设置的。

User Data 里 Custom 框里加入：
DOMAIN-SUFFIX,youtube.com,节点名称,force-remote-dns

**Comment by idenpa** [comment]
@Jumeo7 好的 谢谢 Custom框我找找 在Add那个么？

**Comment by lhie1** [comment]
Done.
