### ISSUE TITLE
豆瓣电影开屏和内置首页的广告

### ISSUE THREAD

**Issue by forward0401** [lhie1/Surge#226]
App名字：豆瓣电影
App链接：https://itunes.apple.com/cn/app/%E8%B1%86%E7%93%A3%E7%94%B5%E5%BD%B1-%E5%85%A8%E5%9B%BD%E5%BD%B1%E8%AE%AF-%E4%BC%98%E6%83%A0%E7%94%B5%E5%BD%B1%E7%A5%A8/id446745748?l=en&mt=8
问题：希望大佬有空抓一下豆瓣电影的开屏和首页横幅广告。
豆瓣电影将豆瓣中获得影单独提出，比豆瓣这个大杂烩。对影视爱好者更加友好

**Comment by rickeylau** [comment]
+1

**Comment by Jumeo7** [comment]
@forward0401 // movie.douban
^https://api.douban.com/v2/app_ads/common_ads - reject
^https://frodo.douban.com/api/v2/movie/banner - reject

**Comment by lhie1** [comment]
Done.
