### ISSUE TITLE
youtube 广告

### ISSUE THREAD

**Issue by rickeylau** [lhie1/Surge#227]
YouTube app 的广告有减少但 并没有都屏蔽掉

**Comment by AnyoeDove** [comment]
顺便说一下 `^https?://r\d{1,2}---sn-.+.googlevideo.com - reject` 这条规则是错误并且没有意义的

**Comment by Jumeo7** [comment]
@AnyoeDove 请您指点一下哪里错误，实在看不出来。谢谢 😋

**Comment by lhie1** [comment]
@Jumeo7 同看不出

**Comment by AnyoeDove** [comment]
简而言之 你看任何一个 YouTube 视频都能匹配 `^https?://r\d{1,2}---sn-.+.googlevideo.com` 这条 因为这是视频播放的来源 详细域名范围参见 https://github.com/lennylxx/ipv6-hosts/blob/master/snippets/08_googlevideo.txt
如果这条生效 YouTube 所有视频都播放不了
而且 YouTube 没有非 https 请求 并且没有相关域名加入MITM的名单中 所以从来没有生效过

**Comment by AnyoeDove** [comment]
YouTube 的广告不好去除 如果没有接收通知的需求 可自行 sideload [JMccormick264/YouTubePP](https://github.com/JMccormick264/YouTubePP/releases) 中的 Patched 的去广告版 YouTube

**Comment by Jumeo7** [comment]
@AnyoeDove 懂了，谢谢。

**Comment by shigalin** [comment]
^https?://r\d{1,2}---sn-.+.googlevideo.com - reject
这条确实导致了我是用第三方app播放视频的时候报错，刚想提个issue。

**Comment by Jumeo7** [comment]
@shigalin 前面有 dalao 解释过了，没有对域名解密，因此这条规则压根就没有起作用。怎么可能会导致你播放视频报错？

**Comment by yinws** [comment]
@Jumeo7 你可以尝试Tubex试试

**Comment by Jumeo7** [comment]
@yinws 这条规则不会屏蔽任何内容

**Comment by shigalin** [comment]
@Jumeo7 你用第三方客户端Tubex试过吗。。。

**Comment by shigalin** [comment]
@shigalin Tubex - New Video Player by Rodick Studio
https://itunes.apple.com/cn/app/tubex-new-video-player/id1271964636?l=en&mt=8
https://itunes.apple.com/cn/app/tubex-new-video-player/id1271964636?l=en&mt=8

**Comment by Jumeo7** [comment]
@shigalin 试过了，确实是这条规则的原因。对不起，对不起。

**Comment by Jumeo7** [comment]
@AnyoeDove dalao，YouTube 是有 http 请求的。

**Comment by AnyoeDove** [comment]
我上面所指的 YouTube 是指的 Google 出的 YouTube App.....第三方的 YouTube APP 基本都去了广告 还去个啥.....
