### ISSUE TITLE
知乎图片问题

### ISSUE THREAD

**Issue by ldldlr** [lhie1/Surge#230]
知乎图片部分加载不出来。尝试了很久，发现是pic2.zhihu.com这个地址的图片，设为direct的话chrome上已解决，但safari时还是不行，看日志，这个地址压根就没访问……实在不知道怎么解决了

**Comment by lhie1** [comment]
@ldldlr 证书

**Comment by ldldlr** [comment]
证书是安装了的哇……需要删了重新装吗

**Comment by ldldlr** [comment]
重新装了证书还是没用…之前把所有知乎相关规则删除了也没用，好奇怪…就只有pic2.zhimg的是这样

**Comment by ldldlr** [comment]
而且日志里直接就没有pic2.zhimg……我把https解密里的这条删了或留着，都是这样… @lhie1

**Comment by lhie1** [comment]
知乎我一直用着正常，也没人反映有问题

请确保正确安装并信任证书

**Comment by giveup** [comment]
see https://github.com/lhie1/Surge/issues/192

**Comment by ldldlr** [comment]
@giveup 多谢。我之前已在关于本机中信任证书，请问您提到的profile具体指哪里的设置呢？

**Comment by giveup** [comment]
@ldldlr 首先安装证书，在 General --> Profile & Device Management，然后是 About 里面的 Certificate Trust Settings。
https://support.apple.com/en-nz/HT204477

**Comment by ldldlr** [comment]
@giveup 嗯，但是我之前已经开启这个了…谢谢耐心解答

**Comment by giveup** [comment]
@ldldlr 另外，你是什么客户端，有可能是你的客户端bug。

**Comment by ldldlr** [comment]
@giveup 最新版shadowsocks2.1.15，ios11.0.3
我曾经改了很多“变量”对比想发现问题，都失败了……最后发现，就算不开ss客户端，貌似在safari上访问pic2.zhimg这个域名的图片都是访问不到的…好像就没有跑流量。chrome上就OK，真是非常奇怪，还好影响不大，已弃疗～
