### ISSUE TITLE
请帮忙屏蔽QQ音乐开屏广告

### ISSUE THREAD

**Issue by pzh950921** [lhie1/Surge#236]
QQ音乐APP，开屏广告，连续四次开屏会出现2次，自己抓包没成功，还请帮忙屏蔽一下，谢谢！
https://itunes.apple.com/cn/app/qq%E9%9F%B3%E4%B9%90-%E6%9D%A5%E8%BF%99%E9%87%8C-%E5%8F%91%E7%8E%B0-%E9%9F%B3%E4%B9%90/id414603431?l=en&mt=8

**Comment by lhie1** [comment]
Done.

**Comment by pzh950921** [comment]
万分感谢！
