### ISSUE TITLE
老司机app开屏广告

### ISSUE THREAD

**Issue by Wangsc1** [lhie1/Surge#237]
麻烦dalao屏蔽下，老司机-汽车新闻视频资讯之家 https://itunes.apple.com/app/id1203105861?at=1001lsTF&ct=iOS_detail_share_1203105861

**Comment by Jumeo7** [comment]
[已屏蔽](https://github.com/lhie1/Surge/commit/90b9c8b717add9017bbe9ce0a1adf130cce38c62#diff-34ead48c776e93fd9a6a383c69598b17)
