### ISSUE TITLE
同花顺至尊版和杭州市民卡开屏广告

### ISSUE THREAD

**Issue by forward0401** [lhie1/Surge#238]
1.app名称：同花顺至尊版
app链接：同花顺至尊版 by Zhejiang Hexin Flush Network Services Ltd
https://itunes.apple.com/cn/app/%E5%90%8C%E8%8A%B1%E9%A1%BA%E8%87%B3%E5%B0%8A%E7%89%88/id954724812?l=en&mt=8
问题描述：同花顺开屏广告
2.app名称：杭州市民卡
app链接：杭州市·市民卡 by Hangzhou Citizen Card Co., Ltd.
https://itunes.apple.com/cn/app/%E6%9D%AD%E5%B7%9E%E5%B8%82-%E5%B8%82%E6%B0%91%E5%8D%A1/id917075932?l=en&mt=8
问题描述：可以请大佬去掉开屏广告吗？

**Comment by Jumeo7** [comment]
[已屏蔽](https://github.com/lhie1/Surge/commit/2ee89d193e3645577d9318234e4ad77cf10f5875)
