### ISSUE TITLE
依然是QQ音乐开屏广告问题

### ISSUE THREAD

**Issue by pzh950921** [lhie1/Surge#239]
使用新的规则之后，QQ音乐重新安装，可以做到暂时不有广告，但几个小时后开启QQ音乐，开屏广告重现，而且次次都有...劳烦大佬再帮忙抓下，谢谢！
https://itunes.apple.com/cn/app/qq%E9%9F%B3%E4%B9%90-%E6%9D%A5%E8%BF%99%E9%87%8C-%E5%8F%91%E7%8E%B0-%E9%9F%B3%E4%B9%90/id414603431?l=en&mt=8

**Comment by Jumeo7** [comment]
@pzh950921 ^http://y.gtimg.cn/music/common/upload/t_splash_info - reject

**Comment by Jumeo7** [comment]
@Jumeo7 修正

^http://.+/music/common/upload/t_splash_info - reject

**Comment by pzh950921** [comment]
@Jumeo7 感谢大佬！好厉害！我怎么抓都抓不对。。。
