### ISSUE TITLE
问题反馈：QQ公告图片资源加载不出来，花生地铁wifi验证失败问题

### ISSUE THREAD

**Issue by microxiao** [lhie1/Surge#240]
QQ公告的图片资源不能加载，不晓得其他地方还有没，没有测试。
花生地铁的WIFI验证问题，这个应该是很多验证都有的吧
高德地图的消息通知可以屏蔽吗

**Comment by lhie1** [comment]
qq公告测试没有问题

公共Wi-Fi验证问题和规则没有关系

消息通知应该是走的apple的推送 不能
