### ISSUE TITLE
抓包广告反馈，如果有用希望作者采纳噢

### ISSUE THREAD

**Issue by xperezxin** [lhie1/Surge#242]
网易云音乐广告:
dongfeng.alicdn.com
df.tanx.com

全民K歌
imgcache.qq.com

image*.suning.cn好像这种写法对小火箭没什么用，只能一条条写(而且我发现有好几条重复的，作者有时间看一下欧)
image1.suning.cn
image2.suning.cn
……

**Comment by Jumeo7** [comment]
@microxiao 东风系统是阿里妈妈的数据分析服务；
tanx.com 是友盟的，其实也就是阿里的，是统计用户数据的；
全民 K 歌是腾讯家的，imgcache 这个子域名也很清楚地说明了它是干什么的了。

很遗憾，三条规则都跟「广告」没什么关系，加油！

**Comment by microxiao** [comment]
最近的网易云音乐就是这个地址，只不过到时候会有不同的广告商罢了

**Comment by lhie1** [comment]
ok 这几天太忙 闲下来会抓

mitm 我尽量不会使用通配符

**Comment by microxiao** [comment]
好的，辛苦大佬了😃

**Comment by Jumeo7** [comment]
@microxiao 妈耶，脸都要被打肿了。

刚才下载了网易云音乐，确实已经引入了阿里的广告。

![cry](https://yt3.ggpht.com/-Gpd4BlGAj7o/AAAAAAAAAAI/AAAAAAAAAAA/FGhDx-vlCBA/s900-c-k-no-mo-rj-c0xffffff/photo.jpg)

**Comment by Jumeo7** [comment]
@microxiao 跟您道歉

脸都要被打肿了，再也不立 Flag 了。

刚才下载了网易云音乐，确实已经引入了阿里的广告，广告图片的地址的确是'dongfeng.alicdn.com'。

但是开屏广告的请求地址没有改变，依然是'http://music.163.com/eapi/ad/'，这部分 dalao 已经屏蔽。

![sad](https://yt3.ggpht.com/-Gpd4BlGAj7o/AAAAAAAAAAI/AAAAAAAAAAA/FGhDx-vlCBA/s900-c-k-no-mo-rj-c0xffffff/photo.jpg)

**Comment by Jumeo7** [comment]
@microxiao 跟您道歉。

脸都要被打肿了，再也不立 Flag 了。

刚才下载了网易云音乐，确实已经引入了阿里的广告，广告图片的地址的确是`dongfeng.alicdn.com`。

但是开屏广告的请求地址没有改变，依然是`http://music.163.com/eapi/ad/`，这部分 dalao 已经屏蔽。

![sad](https://yt3.ggpht.com/-Gpd4BlGAj7o/AAAAAAAAAAI/AAAAAAAAAAA/FGhDx-vlCBA/s900-c-k-no-mo-rj-c0xffffff/photo.jpg)
