### ISSUE TITLE
关于teleplus应用规则

### ISSUE THREAD

**Issue by lorexu** [lhie1/Surge#245]
规则里面有一条guangzhuiyuan.com被reject的规则，在使用teleplus这个app的时候，主题和查看分享的媒体文件功能不能使用。
https://itunes.apple.com/cn/app/teleplus-%E5%BC%BA%E5%A4%A7%E7%9A%84%E9%80%9A%E4%BF%A1%E5%AE%A2%E6%88%B7%E7%AB%AF/id1282906329?mt=8

**Comment by AnyoeDove** [comment]
一个连开源都没有的 Telegram 客户端真的敢用？简介里面直接丢了官方 Telegram 安卓版的开源地址？真的勇敢！

**Comment by lorexu** [comment]
详细看了下，还是决定用官方APP了
