### ISSUE TITLE
和 chrome 插件一起使用会导致 youku 播放失败

### ISSUE THREAD

**Issue by foisonocean** [lhie1/Surge#248]
和此 Chrome 插件一起使用会导致 youku 播放失败
https://chrome.google.com/webstore/detail/yet-another-player-for-yo/fpnknfakcmgkbhccgpgnbaddggjligol

**Comment by lhie1** [comment]
安装证书了吗

**Comment by foisonocean** [comment]
@lhie1 需要安装什么证书？
