### ISSUE TITLE
两个ISP劫持

### ISSUE THREAD

**Issue by TPCTPCTPC** [lhie1/Surge#257]
通过surge抓包得到两个弹红包广告的域名：
momo.popupad.cn
quanliyouxi.cn
不清楚应该用DOMAIN-SUFFIX规则还是URL reject，遂使用前者屏蔽并成功；

查询了V2EX，发现这两个域名是ISP劫持，链接如下：
https://www.v2ex.com/t/401872#r_4948606
https://www.v2ex.com/t/381953#r_4686120

宽带是广东电信 ，软件为即刻app

**Comment by lhie1** [comment]
谢谢
