### ISSUE TITLE
优酷视频无法播放

### ISSUE THREAD

**Issue by ilostin** [lhie1/Surge#262]
这两天发现只要打开surge 优酷视频就会打不开，已经用workflow更新最新的规则了

**Comment by lhie1** [comment]
@ilostin 证书情况呢

**Comment by CyshallChan** [comment]
我也遇到了，配置导致优酷视频无法播放。

**Comment by lhie1** [comment]
@CyshallChan Youku = False

**Comment by CyshallChan** [comment]
![2](https://user-images.githubusercontent.com/22564041/33642724-2d0ec038-da76-11e7-886c-bdb0a162d602.jpg)
![default](https://user-images.githubusercontent.com/22564041/33642722-2875bf2c-da76-11e7-8d49-c8a11a9026fa.jpg)
如图，没有用。

**Comment by lhie1** [comment]
请确定证书是否正常安装并信任

**Comment by CyshallChan** [comment]
证书正常。

**Comment by CyshallChan** [comment]
另外YouTube去广告也失效了。

**Comment by lhie1** [comment]
@CyshallChan Youtube 广告没有屏蔽过 也屏蔽不了

**Comment by CyshallChan** [comment]
我看到有个YouTube开关以为YouTube广告也能屏蔽...
