### ISSUE TITLE
可否做一个去翻墙，保留其他服务的规则

### ISSUE THREAD

**Issue by jwd1208** [lhie1/Surge#264]
家里是路由器翻墙， 但无法屏蔽广告及Apple 加速功能，可否出一个规则，去除翻墙、保留其他功能？
谢谢了

**Comment by lhie1** [comment]
@jwd1208 https://raw.githubusercontent.com/Hsiny/Shadowrocket-Config/master/rulewithad.txt

**Comment by jwd1208** [comment]
这个可以做成workflow导入的模板吗？

**Comment by lhie1** [comment]
你可以尝试一下
