### ISSUE TITLE
Quantumult开启https解密，京东金融无法使用

### ISSUE THREAD

**Issue by dtlg886** [lhie1/Surge#265]
![photo_2017-12-07_15-27-57](https://user-images.githubusercontent.com/34331927/33703475-3a4fa3c8-db63-11e7-8efc-17f0c526d211.jpg)
![photo_2017-12-07_15-27-52](https://user-images.githubusercontent.com/34331927/33703488-477c0cbc-db63-11e7-9547-b27ff9ab531b.jpg)
开启解密后点击无反应或网络错误，关闭后正常。

**Comment by giveup** [comment]
部分app只接受指定证书,请查看Quantumult是否有自定义mitm域名的功能.
