### ISSUE TITLE
反馈几个问题（workflow更新方式）

### ISSUE THREAD

**Issue by ClareChen** [lhie1/Surge#268]
使用了一个无法识别的☁️ Others策略，每次得手动修改。。我改成direct。然后会有下面这些网站有问题：

- 斗鱼直播无法播放视频流

- 知乎一些图片无法加载

- 招行掌上生活APP数据无法加载

**Comment by lhie1** [comment]
@ClareChen 更新 User Data

安装并信任证书

**Comment by ClareChen** [comment]
更新workflow，安装并信任证书。策略问题解决了。但是招行掌上生活仍然无法访问。应该是规则问题？
斗鱼直播流还未尝试…

**Comment by lhie1** [comment]
@ClareChen 关于本机里去信任

**Comment by ClareChen** [comment]
已经安装并信任了证书。确认。

系统版本：iOS 11.2

**Comment by ClareChen** [comment]
sorry ，关闭了https解密，没问题了。

**Comment by lhie1** [comment]
@ClareChen 个别 APP 会出现这种情况，不过你说的这几个 APP 我这边测试下来都是可以正常运行并屏蔽的
