### ISSUE TITLE
iOS知乎4.6.1版本新加入了很多广告，规则失效了。

### ISSUE THREAD

**Issue by Fezreal** [lhie1/Surge#274]
// Zhihu
DOMAIN-SUFFIX,sugar.zhihu.com,REJECT
DOMAIN-SUFFIX,zhihu-analytics.zhihu.com,REJECT
DOMAIN-SUFFIX,zhihu-web-analytics.zhihu.com,REJECT
DOMAIN-SUFFIX,zhstatic.zhihu.com,REJECT

目前的规则不能去除最新版本的知乎广告了，麻烦看一下，谢谢。

**Comment by Jumeo7** [comment]
@Fezreal 开屏广告
^https?://api.zhihu.com/launch - reject
^https?://api.zhihu.com/real_time_launch - reject

时间线上的大图广告
^https?://pic\d.zhimg.com/v\d-\w+_1200x500.jpeg - reject

时间线上的 Live 广告
^https?://api.zhihu.com/lives/special_lists - reject
^https?://api.zhihu.com/market/recommendations/lives - reject

推荐阅读的广告
^https?://www.zhihu.com/api/v\d/answers/\d+?/related-readings - reject
^https?://www.zhihu.com/api/v\d/questions/\d+?/related-readings - reject

评论区的广告
^https?://api.zhihu.com/answers/\d+?/comments/featured-comment-ad - reject

**Comment by Fezreal** [comment]
@Jumeo7
这是什么格式的规则……不是surge的，也不是shadowrocket的。

**Comment by Jumeo7** [comment]
@Fezreal 是 Surge 的，也是 Shadowrocket 的。

**Comment by Fezreal** [comment]
放进surge里面报invalid line

**Comment by Jumeo7** [comment]
@Fezreal 把所有汉字删除

**Comment by Fezreal** [comment]
@Jumeo7 开屏广告去除失败

**Comment by Jumeo7** [comment]
@Fezreal 测试没问题
