### ISSUE TITLE
speedtest无法正常使用。

### ISSUE THREAD

**Issue by Fezreal** [lhie1/Surge#276]
// Google
DOMAIN-SUFFIX,2mdn.net,REJECT
DOMAIN-SUFFIX,ads.gmodules.com,REJECT
DOMAIN-SUFFIX,ads.google.com,REJECT
DOMAIN-SUFFIX,afd.l.google.com,REJECT
DOMAIN-SUFFIX,badad.googleplex.com,REJECT
DOMAIN-SUFFIX,cm.g.doubleclick.net,REJECT
DOMAIN-SUFFIX,doubleclick.com,REJECT
DOMAIN-SUFFIX,doubleclick.net,REJECT
DOMAIN-SUFFIX,googleadsserving.cn,REJECT
DOMAIN-SUFFIX,google-analytics.com,REJECT
DOMAIN-SUFFIX,googlecommerce.com,REJECT
DOMAIN-SUFFIX,googlesyndication.com,REJECT
DOMAIN-SUFFIX,googletagmanager.com,REJECT
DOMAIN-SUFFIX,googletagservices.com,REJECT
DOMAIN-SUFFIX,mm.admob.com,REJECT
DOMAIN-SUFFIX,mobileads.google.com,REJECT
DOMAIN-SUFFIX,pagead.google.com,REJECT
DOMAIN-SUFFIX,pagead.l.google.com,REJECT
DOMAIN-SUFFIX,pagead2.googlesyndication.com,REJECT
DOMAIN-SUFFIX,pagead-tpc.l.google.com,REJECT
DOMAIN-SUFFIX,partner.googleadservices.com,REJECT
DOMAIN-SUFFIX,pubads.g.doubleclick.net,REJECT
DOMAIN-SUFFIX,r.admob.com,REJECT
DOMAIN-SUFFIX,securepubads.g.doubleclick.net,REJECT
DOMAIN-SUFFIX,service.urchin.com,REJECT
DOMAIN-SUFFIX,static.googleadsserving.cn,REJECT
DOMAIN-SUFFIX,tpc.googlesyndication.com,REJECT
DOMAIN-SUFFIX,www.googleadservices.com,REJECT

surge里面的这段规则，导致iOS speedtest最新版本，测速失败。

**Comment by Jumeo7** [comment]
@Fezreal 测试没问题
