### ISSUE TITLE
非wf如何自动更新？

### ISSUE THREAD

**Issue by livc** [lhie1/Surge#28]
🆙 自动更新（示范）

单节点：https://async.be/Rule/Advanced/Surge.php?List=https://raw.githubusercontent.com/lhie1/CloudGate-List/master/Rule/&AutoGroup=false&Rule=false&Apple=false&IPV6=false&Group=1&SERVER1=ServerName,custom,127.0.0.1,80,rc4-md5,Password&DNS=false&AGENT=false

多节点：https://async.be/Rule/Advanced/Surge.php?List=https://raw.githubusercontent.com/lhie1/CloudGate-List/master/Rule/&AutoGroup=false&Rule=false&Apple=false&IPV6=false&Group=2&SERVER1=ServerName,custom,127.0.0.1,80,rc4-md5,Password&SERVER2=ServerName,custom,127.0.0.1,80,rc4-md5,Password&DNS=false&AGENT=false

参数详解：https://manual.async.be/AdvancedRule.html

这个如何自动更新？

**Comment by lhie1** [comment]
示例和详解都有 看看就能明白

**Comment by livc** [comment]
@lhie1 这个自动更新是指自动更新配置文件吗？
原谅我真没看懂怎么用……

**Comment by lhie1** [comment]
是的 每24小时更新一次
