### ISSUE TITLE
知乎无网络连接

### ISSUE THREAD

**Issue by minsnia** [lhie1/Surge#281]

**Comment by lhie1** [comment]
@minsnia 证书

**Comment by CyshallChan** [comment]
我也是这种情况，证书正常。
之前提个issue还没来得及回复就给关了。

**Comment by pzh950921** [comment]
我在ios app用上知乎的广告屏蔽链接，没有出现过无网络连接的问题，在浏览器中使用知乎时出现过“无网络连接”但是还是可以使用。

**Comment by deepcoldy** [comment]
我也出现了这种情况，8plus ios11.2.5，微信打不开https://www.zhihu.com
抓包看了没有通过知乎的流量，但是surge的证书应该是正确安装的，不太理解什么原因，猜测还是证书的问题。

**Comment by deepcoldy** [comment]
多提供点信息：
使用的surge3 ，使用Workflow的Rule OTA自动更新的规则。
![image](https://user-images.githubusercontent.com/10922642/35550132-0a9e6e1c-05c4-11e8-9389-e66e7b1c11da.png)
![image](https://user-images.githubusercontent.com/10922642/35550134-0fb93c1a-05c4-11e8-88f7-c4301f00419f.png)

**Comment by Jumeo7** [comment]
@deepcoldy 测试没有问题

![](https://i.loli.net/2018/01/30/5a7008d5190bb.png)

**Comment by deepcoldy** [comment]
感谢~ 
搜了一下，作者反复强调去信任证书，原来不是光添加描述文件成功就可以了的。
必须在关于本机-证书信任设置里面打开。
找不到的可以直接在设置里搜索关键字“信任”，我是这么找到的。
![image](https://user-images.githubusercontent.com/10922642/35550517-a86f7a54-05c5-11e8-85f3-00b9422dfa7d.png)

**Comment by deepcoldy** [comment]
@CyshallChan 
@minsnia 
@pzh950921 
相信你们都是我这种情况，此issue可以关了。

**Comment by CyshallChan** [comment]
@deepcoldy 我这边确实也是这种情况，感谢各位的解答。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pzh950921** [comment]
@deepcoldy 我和你情况不一样，我只是会显示无连接，但是正常使用的，证书一直是信任的。

**Comment by wrong5210** [comment]
为什么我没有证书信任设置…

**Comment by Jumeo7** [comment]
@wrong5210 因为你没有安装证书

**Comment by wrong5210** [comment]
@Jumeo7 安装了 我看下了下好像ios10才有这个设置 我的是ios9😂

**Comment by Jumeo7** [comment]
@wrong5210 原来是这样，10.3 以后才有的。

**Comment by wrong5210** [comment]
@Jumeo7 那是不是用不了规则了？
