### ISSUE TITLE
抓到一枚应用内广告，求添加

### ISSUE THREAD

**Issue by vxxholic** [lhie1/Surge#282]
应用：[欢乐跳瓶](https://itunes.apple.com/cn/app/%E6%AC%A2%E4%B9%90%E8%B7%B3%E7%93%B6/id1178454068?mt=8)

广告域名：www.ketchapp.org

直接在浏览器里打开这个网站，显示的是Apache 2 Test Page，可以直接屏蔽掉

多谢！

**Comment by lhie1** [comment]
多谢提供
