### ISSUE TITLE
误杀支付宝买车票功能

### ISSUE THREAD

**Issue by CyshallChan** [lhie1/Surge#285]
![GitHawk Upload by CyshallChan](https://i.imgur.com/eWbkBbj.jpg)
如图。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by CyshallChan** [comment]
不是证书问题，不是证书问题，不是证书问题！

**Comment by Jumeo7** [comment]
@CyshallChan 测试没有问题

![](https://i.loli.net/2018/01/03/5a4cb144cdded.png)

**Comment by CyshallChan** [comment]
@Jumeo7 见鬼了，我这边不行了，一换成默认配置就可以了。
对了，我是直接用的远程文件。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
