### ISSUE TITLE
爱奇艺app开屏广告

### ISSUE THREAD

**Issue by pzh950921** [lhie1/Surge#292]
ios端爱奇艺app开屏广告屏蔽不彻底，连续启动app，平均4-5次会出现一次广告。

**Comment by shigalin** [comment]
@pzh950921 随意点了两个没发现广告

**Comment by pzh950921** [comment]
今天尝试了好多次发现没广告了...难道昨天手机出了问题...抱歉添麻烦了...

**Comment by Jumeo7** [comment]
@pzh950921 确实是有广告的，昨天晚上抓到了广告图片，但是特征不明显，不知道怎样屏蔽。

http://dx-pic0.qiyipic.com/common/20171228/8fb7a976c2e348968a495588f3e2364f.jpg
http://dx-pic1.qiyipic.com/common/20180108/5a7963ad03114235bb94b84df74a8b2b.jpg

**Comment by pzh950921** [comment]
@Jumeo7 其实我觉得不止这两张，昨晚发现广告后，连续开关APP一个小时左右，还出现了一张“啥啥排行榜”的广告。看链接像是每天会变更的广告，要不dx-pic后的数字和日期直接使用通配符？会不会误杀很多非广告链接…我这个不懂计算机的小渣渣给大家添麻烦了，捂脸【つ﹏⊂】

**Comment by pzh950921** [comment]
@Jumeo7 厉害！我抓包都抓不准，只能手动反复试错了。

**Comment by pzh950921** [comment]
@Jumeo7 厉害厉害！

**Comment by pzh950921** [comment]
谢谢大神！
