### ISSUE TITLE
知乎app开屏广告

### ISSUE THREAD

**Issue by pzh950921** [lhie1/Surge#295]
我又来了...人肉测得（反复开关）知乎app发现开屏广告不能完全屏蔽，清理缓存以及重装app 后依然存在。...辛苦大神啦！

**Comment by Jumeo7** [comment]
@pzh950921 本来是屏蔽了的，有人反应有问题，dalao 就给删掉了。

不过我用起来没啥问题，你自己加上吧。

^https?://api.zhihu.com/launch - reject
^https?://api.zhihu.com/real_time_launch - reject

需要针对 api.zhihu.com 解密。

**Comment by pzh950921** [comment]
@Jumeo7 原来如此！谢谢大神！
