### ISSUE TITLE
请求过滤一个很好的app的广告。

### ISSUE THREAD

**Issue by Fezreal** [lhie1/Surge#297]
https://itunes.apple.com/us/app/isafeplay/id478653772?mt=8
这个app广告真的神多。
不过这个app是真的好用，因为NSFW我就不详细说了，大佬可以自己体验一下。
特别是VR资源。。。。

**Comment by Jumeo7** [comment]
这个应用使用的是 Google 广告，不需要额外屏蔽。

**Comment by Jumeo7** [comment]
这个应用使用的是 Google 广告，已经屏蔽，不需要额外的屏蔽。
