### ISSUE TITLE
iqiyi正常图片无法显示

### ISSUE THREAD

**Issue by coolkid1900** [lhie1/Surge#31]
经测试删除^.+pic\d{1}.qiyipic.com/common _ reject规则可以正常显示封面等图片，并不影响app视频去广告

**Comment by lhie1** [comment]
这是我抓的app内的广告

请问不能显示的是什么封面？

**Comment by coolkid1900** [comment]
就是pic+数字的这条正则规则会导致本来应该正常显示的剧集封面等图片不显示或者加载十分缓慢

**Comment by lhie1** [comment]
有时间我再看看
