### ISSUE TITLE
QQ音乐部分页面被拦截，无法加载

### ISSUE THREAD

**Issue by zealson** [lhie1/Surge#318]
如图所示，部分图片加载不出来，歌单加载不出来，关闭代理可完全正常加载显示，麻烦请处理下，谢谢!

![Image](https://i.imgur.com/W3RoZAD.jpg)
![Image](https://i.imgur.com/NJDB1BU.jpg)

**Comment by yinws** [comment]
并没有

使用的app是哪个呢？

**Comment by lhie1** [comment]
测试没有此问题
