### ISSUE TITLE
希望屏蔽有道词典的广告

### ISSUE THREAD

**Issue by menyf** [lhie1/Surge#32]
1. 有道词典的广告，不清楚要怎么才能屏蔽掉，是HTTPS的
![img_1092](https://cloud.githubusercontent.com/assets/14975390/22928340/ebe06854-f2f0-11e6-82b2-afae5417f2a3.PNG)

2. 希望对于直接Reject的Domain设置一个Select规则`🙅AdBlock = select, 🌍 Direct, ☁️ Proxy, REJECT`，因为有的时候REJECT广告会将不应该屏蔽的内容也屏蔽了

感谢制作规则🙏

**Comment by lhie1** [comment]
不过顺便把启动广告屏蔽了
