### ISSUE TITLE
多节点的自动更新有问题

### ISSUE THREAD

**Issue by williamdong90** [lhie1/Surge#33]
多节点：https://async.be/Rule/Advanced/Surge.php?List=https://raw.githubusercontent.com/lhie1/CloudGate-List/master/Rule/&AutoGroup=false&Rule=false&Apple=false&IPV6=false&Group=2&SERVER1=ServerName,custom,127.0.0.1,80,rc4-md5,Password&SERVER2=ServerName,custom,127.0.0.1,80,rc4-md5,Password&DNS=false&AGENT=false
2282行会产生  DOMAIN-SUFFIX,zzsx8.com,REJECTDOMAIN-KEYWORD,content.icloud,DIRECT,force-remote-dns 
reject和domain没有分行，会报错，无法导入

**Comment by lhie1** [comment]
谢谢 已修复
