### ISSUE TITLE
即刻关注页有时无法刷新，但是多刷新几次也能刷出来，

### ISSUE THREAD

**Issue by ciscotr** [lhie1/Surge#330]
![_20180129235507](https://user-images.githubusercontent.com/35926327/35519679-df26297e-054f-11e8-9b2f-b104a27b90d6.jpg)
评论页面有时候也会这样，再次刷新就好了，关注页面加载也比关闭ssr时慢得多
iPhone 6sp，iOS11.2.5，quantumult

**Comment by hazxy** [comment]
se 10.3.3 小火箭同样与这个问题，关了就好了

**Comment by Rhysn** [comment]
关掉https解密，或者去除解密ruguoapp.com

**Comment by lhie1** [comment]
偶尔会出现这种情况，预测和证书有关

一般遇到这种情况可以尝试检查或重新安装证书，或从 hostname 里删除 `app.jike.ruguoapp.com`
