### ISSUE TITLE
搜狐视频无法播放

### ISSUE THREAD

**Issue by ciscotr** [lhie1/Surge#335]
手机和hd版本都无法播放，缓存也清除过了

**Comment by shigalin** [comment]
已修改

**Comment by shigalin** [comment]
@ciscotr 截图播放失败时的最近请求吧，我这边正常。

**Comment by shigalin** [comment]
@ciscotr 你是url规则更新了吗？

**Comment by ciscotr** [comment]
@shigalin 刚才发现把filter里的reject改为direct，然后rejection规则保留，就正常了

**Comment by shigalin** [comment]
@ciscotr 你更新下规则，然后删除以下三条试试：
DOMAIN-SUFFIX,count.vrs.sohu.com,REJECT
DOMAIN-SUFFIX,info.lm.tv.sohu.com,REJECT
DOMAIN-SUFFIX,mb.hd.sohu.com.cn,REJECT

具体哪条我还没抓，你先把这三条删了看看

**Comment by shigalin** [comment]
已修改，可关闭
