### ISSUE TITLE
Pushbullet无法正常使用

### ISSUE THREAD

**Issue by vxxholic** [lhie1/Surge#343]
去掉下面这条规则以后恢复正常使用
`DOMAIN-SUFFIX,app-measurement.com,REJECT`

![1517838250873](https://user-images.githubusercontent.com/7752687/35807536-0737ed76-0abe-11e8-95c6-0cbd80a5888a.jpg)

**Comment by shigalin** [comment]
好

**Comment by shigalin** [comment]
经测试，并没有问题
