### ISSUE TITLE
开启⭕️后无法使用Siri

### ISSUE THREAD

**Issue by openviso** [lhie1/Surge#352]

**Comment by shigalin** [comment]
@openviso 如果你State选择DIRECT之后失败，建议发邮件给作者。

**Comment by shigalin** [comment]
非规则问题，此Issues可关闭。

Test how it goes, only for DIRECT state.

1. Do NOT hide VPN status icon.
2. Stop Quantumult, switch state to DIRECT, Start Quantumult.
3. Test Siri.

By the way, do NOT switch state to test when Quantumult is connected, please test it in a clean start;
Meaning if you switched state, need to reconnect manually to test Siri.
