### ISSUE TITLE
知乎APP内显示不完整

### ISSUE THREAD

**Issue by ciscotr** [lhie1/Surge#354]
界面内少点东西，不过不影响使用，把zhstatic.zhihu.com这条的reject改成direct就正常了
![_20180216002753](https://user-images.githubusercontent.com/35926327/36268035-6db1bc0e-12b0-11e8-925f-ef6046717399.jpg)

修改前
![_20180216002745](https://user-images.githubusercontent.com/35926327/36268042-72b053dc-12b0-11e8-8f01-fc7dc83ed671.jpg)
修改后

**Comment by lhie1** [comment]
fix
