### ISSUE TITLE
shadowrocket使用规则后无法访问v2ex

### ISSUE THREAD

**Issue by icybest** [lhie1/Surge#361]
如题，shadowrocket使用规则后无法访问v2ex以及一些v2ex的客户端(如v2er)，使用shadowrocket自带的default.conf则可以正常访问，我试过自行排查问题，跟v2ex相关的规则只有一条 DOMAIN-SUFFIX v2ex.com DIRECT ，设置是DIRECT按道理来说应该不会有影响，但实际上删除这条规则之后能够正常访问，我考虑过是不是证书的问题的，也重新导入了证书和清缓存，问题依旧，不知道是我个体的问题，还是哪里存在问题。

**Comment by Jumeo7** [comment]
会不会是 DNS 的问题呢。解析到的是国外的 IP，所以直连困难。而删掉 `DOMAIN-SUFFIX,v2ex.com,DIRECT` 后走 `FINAL,Proxy` 所以访问正常。

**Comment by lhie1** [comment]
DNS 的问题
