### ISSUE TITLE
更新了最新的规则，出现了这个错误

### ISSUE THREAD

**Issue by reaCodes** [lhie1/Surge#365]
![img_1084](https://user-images.githubusercontent.com/13817254/36673412-adc81fa0-1b3d-11e8-8fc6-856f11d73557.PNG)

**Comment by Huang-Libo** [comment]
同样的问题, 环境: iOS 11.2.6,  Surge 2.6.5(Build 1003)

**Comment by reaCodes** [comment]
@Huang-Libo  跟我的环境一样、一气之下把Surge删掉了，用上了Quantumult，很爽

**Comment by lhie1** [comment]
不是使用的 Workflow 吧？

**Comment by reaCodes** [comment]
没有使用

**Comment by lhie1** [comment]
Surge 一直都建议使用 Workflow 导入（URL 版刚刚已经提交更新修复）
Shadworcoekt / Quantumult 都建议使用 URL 直接订阅/导入

**Comment by reaCodes** [comment]
我后来发现，只是你这个规则，很多其他作者的规则，都不好使了，我推测不是规则的原因。只有极少数规则很短，且结构特别简单的规则才能使用。

**Comment by Jumeo7** [comment]
@reaCodes @Huang-Libo iOS 11.2.6，Surge 2.7.1 Build 1099。我用的规则里也包含这一条，但是没有提示错误。建议你们更新到最新的 2.7.1 版本再看看。

**Comment by Huang-Libo** [comment]
说到升级surge, 我发现surge作者在国区上架了 surge 3, 升级费用29刀或49刀, 以前99刀买入的老用户, 现在还得再交29刀升级. 只在手机上翻个墙而已, 就得花一百多刀? 我不理解.

所以美区用户还是用 `Shadworcoekt` 吧, 国区也有 [SsrConnectPro](https://itunes.apple.com/us/app/ssrconnectpro/id1272045249?mt=8), 功能少一点但是翻墙绝对够用了. 免广告可以再下一个 [猎飞](https://itunes.apple.com/cn/app/%E7%8C%8E%E9%A3%9E%E5%B9%BF%E5%91%8A%E6%8B%A6%E6%88%AA-%E5%87%80%E7%BD%91%E5%A4%A7%E5%B8%88-%E5%B9%BF%E5%91%8A%E8%BF%87%E6%BB%A4/id1190177877?mt=8).

**Comment by lhie1** [comment]
@Huang-Libo 不一定非要升级阿
