### ISSUE TITLE
one drive无法上传

### ISSUE THREAD

**Issue by wrong5210** [lhie1/Surge#366]
使用shadowrocket规则无法上传（速度极慢）文件到one drive

**Comment by lhie1** [comment]
速度取决于你服务器的速度

**Comment by wrong5210** [comment]
lhie1 关掉vpn之后速度就很快

**Comment by shigalin** [comment]
@wrong5210 看看hosts里面有木有OneDrive的部分，删除掉再试试

**Comment by wrong5210** [comment]
@shigalin 谢谢快多了
