### ISSUE TITLE
网易云音乐启动界面广告

### ISSUE THREAD

**Issue by reaCodes** [lhie1/Surge#368]
![img_1092](https://user-images.githubusercontent.com/13817254/36715233-499f0816-1bd0-11e8-8960-4cc9d286eed7.PNG)

能不能移除这个广告，喜马拉雅FM启动广告和APP内广告都没有了，我觉得这个应该也能移除吧

**Comment by Jumeo7** [comment]
已屏蔽，Close 吧。

**Comment by reaCodes** [comment]
@Jumeo7 使用哪一个REJECT规则？`Quantumult_URL.conf`这个文件似乎没有得到更新。
