### ISSUE TITLE
凤凰秀三秒启动页

### ISSUE THREAD

**Issue by xipuxipu** [lhie1/Surge#379]
鳳凰秀 来自 Phoenix Hong Kong Television Limitedhttps://itunes.apple.com/cn/app/%E9%B3%B3%E5%87%B0%E7%A7%80/id1300009032?mt=8
大佬给看看

**Comment by Jumeo7** [comment]
[已屏蔽](https://github.com/lhie1/Surge/commit/e511080d7447877836598e0351ca1a092fc33d3d)
