### ISSUE TITLE
app埋堆堆的启屏三秒

### ISSUE THREAD

**Issue by xipuxipu** [lhie1/Surge#389]
埋堆堆 来自 TVBC Network Information Technology Limited
港剧神器

**Comment by xipuxipu** [comment]
埋堆堆 来自 TVBC Network Information Technology Limitedhttps://itunes.apple.com/cn/app/%E5%9F%8B%E5%A0%86%E5%A0%86/id1314769817?mt=8

**Comment by Jumeo7** [comment]
[已屏蔽](https://github.com/lhie1/Surge/commit/3a96b9cef557b3a0acefe7b10eb955f1cb053f9f)
