### ISSUE TITLE
[URL Rewrite]里面将google资源重定位到国内cdn是否可行？

### ISSUE THREAD

**Issue by hegya** [lhie1/Surge#393]
类似于chrome中gooreplacer功能，比如
fonts.googleapis.com => https://fonts.cat.net
secure.gravatar.com => https://gravatar.cat.net
规则应该怎么写？谢谢。

**Comment by lhie1** [comment]
^https?://fonts.googleapis.com https://fonts.cat.net 302
^https?://secure.gravatar.com https://gravatar.cat.net 302
