### ISSUE TITLE
国区 Apple Music 提示"无可用资源" 

### ISSUE THREAD

**Issue by MichaelMa2014** [lhie1/Surge#402]
使用 Shadowrocket 下载 https://github.com/lhie1/Surge/raw/master/Shadowrocket.conf 并启用，点击任意国区 Apple Music 未下载音乐即可复现。

**Comment by MichaelMa2014** [comment]
Log 里面可以看到 Music 访问的所有网址都是 apple.com 结尾的，而且都已经走了 DIRECT，不知道为什么无法播放……另外问题只在联通 4G 出现，连接 Wi-Fi 就可以播放了……诡异

**Comment by oxoxoxox** [comment]
@MichaelMa2014 没什么诡异的 联通自己的网络问题 和手机app或者规则都没关系 你要想在联通网络下使用AppleMusic  那就让AppleMusic相关的请求都走proxy好了

**Comment by MichaelMa2014** [comment]
很诡异啊，因为直接关闭 shadowrocket 的时候是可以正常播放的。

Sincerely,
Chenxiao Ma

**Comment by oxoxoxox** [comment]
@MichaelMa2014 检查DNS  去掉所有的自定义  只使用system

**Comment by lhie1** [comment]
这个应该和 DNS 污染有关系（总之不是规则的问题
