### ISSUE TITLE
请问 Workflow 中的 user data 可以获取其他脚本的内容吗？

### ISSUE THREAD

**Issue by mTerminal** [lhie1/Surge#403]
作者你好，现在有 user data 和 rule data 两个脚本，但是每次更新都会覆盖之前的，这样的话自定义的一些内容就会丢失（节点和自定义规则），想请问一下可以在这两个脚本之外再写一个脚本么？或者多个脚本，只是为了保存节点和自定义规则，这样的话，每次更新 user data 或者 rule data 就不用来回复制粘贴了。
我不知道这个可不可以实现，因为不太懂 Workflow，所以提问请教一下。😁

**Comment by lhie1** [comment]
User Data 之所以只有更新提醒而没有自动更新的功能，原因有亮点
1. 几乎很少更新
2. 给你们充分的时间准备手动升级

Rule OTA 一共也才几个开关，自动更新以后重新开关就行了

虽然可以实现读取，但再写个脚本不现实了
