### ISSUE TITLE
VSCO app 及 官网屏蔽中国 IP

### ISSUE THREAD

**Issue by akimotoakira** [lhie1/Surge#42]
VSCO 的 app 及 官网屏蔽了中国 IP，
官网 vsco.co 仅显示下载链接，
手机 app 则只显示 neocha 一个账号的内容，
且屏蔽了所有社交功能。
尝试了添加 DOMAIN(DOMAIN-SUFFIX),vsco.co,🔰 Proxy 似乎不起作用，
想知道如何添加规则？

**Comment by lhie1** [comment]
我测试没有任何问题

**Comment by akimotoakira** [comment]
是吗……VSCO 官网挂全局代理，是黑色底的很多链接的网页，没挂的话是一个 app store 和豌豆荚的下载网页。我这边一定要 🔰 Proxy 选择 ☁️ Proxy 才能正常访问全功能网页。

**Comment by lhie1** [comment]
😅我确定测试没有任何问题
