### ISSUE TITLE
建议在conf当中增加# Update Time#  2017-03-02 14:29

### ISSUE THREAD

**Issue by badsirius** [lhie1/Surge#46]
建议在conf当中增加# Update Time  或者 # Edited Time
`# Update Time: 2017-03-02 14:29:01 `
or
`# lhie1 Edited: 2017/3/2 Thursday 14:37:31`

如果可能，加上简单的 # Update History

**Comment by lhie1** [comment]
有更新日志 也可以看 Github 记录
