### ISSUE TITLE
ipad优酷app视频广告不能屏蔽

### ISSUE THREAD

**Issue by coolkid1900** [lhie1/Surge#48]
ipad不行，iphone可以，貌似和优酷新版app把正常数据和广告数据一起发送有关，不知道有木有解决办法

**Comment by lhie1** [comment]
iPhone 和 iPad 的广告好像是不一样

iPad 版的优酷可能不会兼容了

**Comment by billysingo** [comment]
好像开启mitm并且把youku.com加进host里还是能去掉的

**Comment by lhie1** [comment]
*.youku.com 吗

我去借个 iPad 测试一下

**Comment by billysingo** [comment]
规则里的优酷相关的header还得改成302吧

**Comment by billysingo** [comment]
我是加了ykimg.com gtimg.cn 和youku.com这三个hostname 然后把优酷相关的header跳转改为302模式就行了

**Comment by lhie1** [comment]
一直在找什么办法..

**Comment by lhie1** [comment]
原来在 issues

**Comment by xiaosan0318** [comment]
我用的1.2.6版本 ，好像不支持mitm，怎么设置302去掉ipad优酷广告呢？

**Comment by lhie1** [comment]
我替换为 302 还是不行

**Comment by billysingo** [comment]
试了一下。用了*.youku.com这个host加到mitm里就行了

**Comment by lhie1** [comment]
更新到最新的规则 然后再试试 好像可以了
