### ISSUE TITLE
mob.com 这个规则去掉吧

### ISSUE THREAD

**Issue by VinkenCheng** [lhie1/Surge#50]
DOMAIN-SUFFIX,mob.com,REJECT 这个规则去掉吧

**Comment by VinkenCheng** [comment]
cdn-apple.com这个规则直接去掉之后，在广东这边貌似apple的服务器ip解析会速度快点，走DIRECT老是会解析不出来。

**Comment by VinkenCheng** [comment]
广州地铁这边连 wifi 需要将 captive.apple.com, *.wifi8.com 这两个加到 skip-proxy 里面

**Comment by lhie1** [comment]
好的 我会修正

**Comment by lhie1** [comment]
这些是属于数据统计类网站 所以被屏蔽了
