### ISSUE TITLE
使用这个surge规则之后，http://www.dji.com/cn/flysafe/no-fly无法正常打开

### ISSUE THREAD

**Issue by Chandler-Lu** [lhie1/Surge#57]
![qq20170319-214006](https://cloud.githubusercontent.com/assets/18322610/24081342/a7e33896-0cec-11e7-860e-fbf03f126bb9.jpg)
打开http://www.dji.com/cn/flysafe/no-fly后，上图中的飞行区域限制无法正常显示，地图无法正常打开～不知道能不能排查一下，谢谢

**Comment by lhie1** [comment]
大致排查了一下 暂时还不知道什么情况
