### ISSUE TITLE
屏蔽了好多的公用WI-FI登录界面

### ISSUE THREAD

**Issue by Chobary** [lhie1/Surge#6]
我在使用此配置文件时，发现无法打开诸如我们单位所提供的公用Wi-Fi的网页登录界面。

**Comment by lhie1** [comment]
并不是屏蔽了公用Wi-Fi的网页登陆页面

可以考虑添加以下规则解决：

[SSID Setting]
"你们单位所提供的公用 Wi-Fi 的 SSID" suspend=true

**Comment by Chobary** [comment]
多谢，我去试试

**Comment by lhie1** [comment]
不客气
