### ISSUE TITLE
empty (sub)expression

### ISSUE THREAD

**Issue by cute** [lhie1/Surge#62]
正则
`(api|ps|sv|offnavi|newvector|ulog\.imap|newloc)(\.map|)\.(baidu|n\.shifen)\.com _ reject`
改为
`(api|ps|sv|offnavi|newvector|ulog\.imap|newloc)(\.map)?\.(baidu|n\.shifen)\.com _ reject`

**Comment by lhie1** [comment]
好的 谢谢
