### ISSUE TITLE
ss的加密算法可以用哪些呢？

### ISSUE THREAD

**Issue by foisonocean** [lhie1/Surge#7]
我这边试了下，我这里试了几种加密方式，好像只有`rc4-md5`可以使用，`aes-256-cfb`和`chacha20`我试了下，好像都不行

**Comment by lhie1** [comment]
rc4-md5 和 aes-256-cfb 是目前为止使用最广泛也最普遍的，如果想使用 chacha20 还需要在 vps 上安装

**Comment by lhie1** [comment]
rc4-md5 和 aes-256-cfb 是目前为止使用最广泛也最普遍的，如果想使用 chacha20 还需要在 vps 上安装libsodium

https://github.com/jedisct1/libsodium

**Comment by foisonocean** [comment]
@lhie1 
### 服务器端没有问题，我自己搭建的服务，用ShadowsocksX连接都没有问题，用surge就连不上了。
### 我排查了下，好像是surge本身的问题，如果我在Surge.conf里填写密码的时候，这个密码里包含`@`这样的符号，好像并不能被Surge正确识别

**Comment by lhie1** [comment]
Surge 支持 SS-libev 全部加密方式

**Comment by foisonocean** [comment]
@lhie1 已经解决了哈，可以close issue了
