### ISSUE TITLE
请问下载好规则之后怎么添加SS账号

### ISSUE THREAD

**Issue by jigsaw1314** [lhie1/Surge#72]
请问下载好规则之后怎么添加SS账号

**Comment by langyapojun** [comment]
如果是surge的话
<code>
🇺🇸 US = custom,us.com,1234,rc4-md5,password,http://omgib13x8.bkt.clouddn.com/SSEncrypt.module

🇭🇰 HK = custom,hk.com,1234,rc4-md5,password,http://omgib13x8.bkt.clouddn.com/SSEncrypt.module

🇯🇵 JP = custom,jp.com,1234,rc4-md5,password,http://omgib13x8.bkt.clouddn.com/SSEncrypt.module

🇸🇬 SG = custom,sg.com,1234,rc4-md5,password,http://omgib13x8.bkt.clouddn.com/SSEncrypt.module
</code>

**Comment by lhie1** [comment]
*.com 部分 - 服务器地址
1234 - 端口
rc4-md5 - 加密方式
password - 密码
