### ISSUE TITLE
日志无Reject，Surge正常登陆，Shadowrocket无法登陆？

### ISSUE THREAD

**Issue by lovedufenk** [lhie1/Surge#73]
请教一个问题，使用海通证券App的时候Surge可以正常登陆，但是小火箭在配置模式下登陆不了，只有切换直连才行，关键配置模式看日志又全是Direct，也无Reject，其他人的规则也这样，应该如何下手排除问题？谢谢。

**Comment by lhie1** [comment]
应该是 bug，重启一下设备
