### ISSUE TITLE
亲，最新版的优酷不能去广告了

### ISSUE THREAD

**Issue by palese** [lhie1/Surge#75]
求更新

**Comment by myme5261314** [comment]
好像部分短视频还能去广告，长的不行了。

**Comment by billysingo** [comment]
开MitM了没。最新的需要开启并且加相应内容至hostname

**Comment by myme5261314** [comment]
@billysingo 可以解释一下吗，MitM在哪里开，好像google了一圈，只搜到在surge for mac里面有这么个选项？ 然后`相应内容是指什么`？
谢谢！

**Comment by palese** [comment]
@billysingo 最新版的规则配合最新版的优酷，如果开了MITM后视频全都不能播放，一直提示网络错误，我目前是把优酷降级到老版本在使用，老版本仍然可以去广告

**Comment by lhie1** [comment]
如果使用最新规则无法正常观看优酷视频
请将 ups.youku.com 从 hostname 中删除

删除后即代表无法使用免费观看会员视频的功能

**Comment by myme5261314** [comment]
@lhie1 不知道理解对不对。
是指将 [`Hostname`](https://github.com/lhie1/Surge/blob/master/Hostname)的内容加到 [`Surge.conf`](https://github.com/lhie1/Surge/blob/master/Surge.conf) 末尾吗？可是好像格式不对，而且好像目前MITM功能只有Surge for Mac支持？ https://trello.com/c/385rDM7V/37-surge-mitm
> [MITM]
// hostname
// MITM

**Comment by palese** [comment]
@myme5261314
//hostname
hostname = 那些个域名

**Comment by palese** [comment]
我发现用最新的规则在最新的优酷上不能用，但优酷有个先锋版，可以用，还能看会员电影

**Comment by lhie1** [comment]
https://t.me/rulenews 有详细的讲解与介绍

**Comment by AemonChan** [comment]
能不能不要代理？我只想去视频（优酷）去广告，按照你的设置好像代理的部分出错，弄不了

**Comment by lhie1** [comment]
因为加了IP检测 最好使用代理才好

**Comment by MurrddoL** [comment]
最新规则用在最新版的优酷HD不能去广告 @lhie1
