### ISSUE TITLE
微信某公众号内订餐功能    不能正常获取地理位置

### ISSUE THREAD

**Issue by sh3rry** [lhie1/Surge#77]
地址：
http://weixin.keruyun.com/shop/wmList?uniqueId=WM&shopId=810006766&brandId=null
还没有具体定位到是哪个数据被REJECT导致的，请查看。

开启状态不能正常获取：
![9 23zdp6tlzdcuuf 0 z k](https://cloud.githubusercontent.com/assets/9400373/25066546/395c5c3e-225b-11e7-80a2-25e3df520f17.png)

关闭状态正常获取位置：
![wyr65hb1x1qz 4sy s 0 8](https://cloud.githubusercontent.com/assets/9400373/25066547/3a3f45bc-225b-11e7-86f8-68006ba6baf6.png)

**Comment by lhie1** [comment]
可能和 growingio.com 或 hm.baidu.com 的拦截有关

请尝试删除测试

**Comment by sh3rry** [comment]
@lhie1 测试为 api.map.baidu.com 位于正则

**Comment by sh3rry** [comment]
@lhie1 测试为 api.map.baidu.com 拦截 位于正则 
(api|ps|sv|offnavi|newvector|ulog\.imap|newloc)(\.map)?\.(baidu|n\.shifen)\.com _ reject
建议修改为：
(ps|sv|offnavi|newvector|ulog\.imap|newloc)(\.map)?\.(baidu|n\.shifen)\.com _ reject

**Comment by lhie1** [comment]
好的

**Comment by lhie1** [comment]
删除以后还是无法定位

**Comment by lhie1** [comment]
而且这个地址是 *.baidu.shifen.com

**Comment by lhie1** [comment]
现在可以定位了..

**Comment by sh3rry** [comment]
ok
