### ISSUE TITLE
红苹果是怎么回事 我只能挨个删除

### ISSUE THREAD

**Issue by coderykw** [lhie1/Surge#78]
红苹果是怎么回事 我只能挨个删除**..**

**Comment by lhie1** [comment]
Proxy Group 模块里没有 🍎 Proxy 这个分支

**Comment by myme5261314** [comment]
可以复制一个其他规则，把其中换成红苹果（direct或代理）

**Comment by palese** [comment]
@coderykw 新最版的surge配合最新版的规则，:apple: Proxy正常使用中
