### ISSUE TITLE
‘’✈️ Proxy‘‘’导致无法benchmark，全部替换成‘’Proxy‘’后正常。

### ISSUE THREAD

**Issue by wakeyale** [lhie1/Surge#8]

**Comment by wakeyale** [comment]
‘’✈️ Proxy‘’导致无法benchmark，全部替换成‘’Proxy‘’后正常。

**Comment by lhie1** [comment]
它们毫无关系 是可以 benchmark 的

**Comment by wakeyale** [comment]
![2016-11-4 08 07 26](https://cloud.githubusercontent.com/assets/23205928/19990160/829dce20-a266-11e6-8206-c178424bf52d.png)
![2016-11-4 08 04 42](https://cloud.githubusercontent.com/assets/23205928/19990175/a8b6889a-a266-11e6-9eff-9229b03755c8.png)

**Comment by wakeyale** [comment]
我也不知道是怎么回事，最开始还分“sure.conf"和”sure pro.conf“的时候，我一直用基础版的，benchmark都是正常的，后来合并后用”sure.conf"发现benchmark都是failed，后来对比原来基础版发现区别就是”proxy“有小飞机和小飞机的区别。。。

**Comment by lhie1** [comment]
也许是你的名称没有对齐？
