### ISSUE TITLE
DNS自动变为240.0.0.2

### ISSUE THREAD

**Issue by tufu9441** [lhie1/Surge#81]
我使用如下url在surge中添加了托管规则：
```
https://async.be/Rule/Advanced/Surge/?List=https://raw.githubusercontent.com/lhie1/CloudGate-List/master/Rule/&AutoGroup=select&Rule=false&Apple=true&IPV6=true&Group=3&SERVER1=US,custom,xxx.xx.xxx.xx,501,aes-256-cfb,12345678&SERVER2=JP,custom,xxx.xx.xxx.xx,501,aes-256-cfb,12345678&SERVER3=Bandwagon,custom,xxx.xx.xxx.xx,443,aes-256-cfb,12345678&DNS=true,2,119.29.29.29,1.2.4.8&AGENT=false
```
使用过程中macbook系统中wifi的dns地址会不定期地自动变为240.0.0.2，删除或者更改后过一段时间又会变回来。看了一下没有什么地方提到过240.0.0.2这个地址啊，好奇怪

![](http://i.imgur.com/XfKrCt7.jpg)

**Comment by sh3rry** [comment]
这个是正常的，这个应该是surge配置的本地的dns，实际上还是用配置文件里面DNS来解析的。
跟路由器DHCP分配的192.168.1.1的dns一样道理，实际使用的DNS还是wan口设置里面的（没设置的话就是运营商分配的）。

**Comment by tufu9441** [comment]
我又搜索了一下，有一篇[帖子](https://www.slahser.com/2016/10/03/Migrate-fish88-to-Surge/)说，配置文件中dns-server一行填的第一个system会被替换成240.0.0.2，是这样吗？
![](http://i.imgur.com/6faFpqG.jpg)

这里提到的配置文件即这里的。

**Comment by sh3rry** [comment]
因为我没有surge for mac，你可以自己测试一下。
 另外，这里的system指的是路由器分配的dns，可能是1个也可能是n个。
 dns-server = system,223.5.5.5,223.6.6.6,119.29.29.29,114.114.114.114 路由器分配的dns，加上后面这些dns作为解析。如果你不想用的话，直接删掉也是没什么关系的。

**Comment by sh3rry** [comment]
240.0.0.2 这个本来就是保留地址啊 。。。目前看就是是surge for mac分配的了

**Comment by tufu9441** [comment]
原来如此，那我了解了，多谢！
