### ISSUE TITLE
腾讯视频客户端不能屏蔽广告

### ISSUE THREAD

**Issue by tufu9441** [lhie1/Surge#82]
用iOS上的腾讯视频APP播放视频时总是会播放广告，没有屏蔽的效果，请问这是本来就无法屏蔽还是规则出了问题呢？谢谢！

![](http://i.imgur.com/Q7TkhAJ.jpg)

**Comment by lhie1** [comment]
可能更新来广告投放的方案

**Comment by kiongweidong** [comment]
我每次都是先把广告屏蔽了然后在提示说仅在大陆地区提供，然后在关闭掉小火箭才能播放！
