### ISSUE TITLE
shadowrocket 阴阳师不能登录

### ISSUE THREAD

**Issue by sh3rry** [lhie1/Surge#84]
## 另外，朋友用的surge加最新配置是正常的，只有shadowrocket有这个问题。

![2](https://cloud.githubusercontent.com/assets/9400373/25273067/c5e8e05e-26bc-11e7-8efa-69b758a14895.jpg)

**Comment by sh3rry** [comment]
@lhie1  #83 我直接在这边回复了，之前手抖没弄好，结果又重开一个。
先直接说结果了，我又测试了很长时间，还是不能登陆，**目前看来不是配置文件的问题**。
因为我切换到了default配置文件，甚至将首页的全局路由从"配置"改到"代理"还是不正常。（前提:节点正常）
但是当我切换为"直连"或者直接关掉shadowrocket马上正常了
既然不是配置问题，这个奇葩的故障我之后有时间自己再研究了，不打扰你了。

**Comment by sh3rry** [comment]
@lhie1 另外，我在测试的时候，因为走了弯路，对比了surge和shadowrocket的配置文件，然后发现有以下几个地方不同。
1. shadowrocket有bypass-tun = xx ，surge没有，surge支持bypass-tun 。  >>还没理解这个参数是什么作用
2.surge有dns-server = xx， shadowrocket支持dns-server，但是没有   >> 这个可以加进去
3. shadowrocket有 DOMAIN-SUFFIX,pstatp.com   ， surge没有  >>  这个可以删掉。
4.surge有 DOMAIN-SUFFIX,burpsuite.applinzi.com   和  DOMAIN-SUFFIX,async.be   shadowrocket没有 >> 这个可以加进去
其他都是完全相同了。

**Comment by lhie1** [comment]
可能是小火箭的bug 我用 Surge 没有任何问题
