### ISSUE TITLE
URL Rewrite的other里有好些个重复项目

### ISSUE THREAD

**Issue by palese** [lhie1/Surge#85]
RT

**Comment by palese** [comment]
^https?://m.+.china.com.cn/statics/sdmobile/js/ad - reject
^https?://m.+.china.com.cn/statics/sdmobile/js/ad _ reject
^https?://m.+.china.com.cn/statics/sdmobile/js/mobile.advert.js - reject
^https?://m.+.china.com.cn/statics/sdmobile/js/mobile.advert.js _ reject
^https?://m.+.china.com.cn/statics/sdmobile/js/mobileshare.js - reject
^https?://m.+.china.com.cn/statics/sdmobile/js/mobileshare.js _ reject
一个减号的，一个下划线的

**Comment by lhie1** [comment]
好的

**Comment by lhie1** [comment]
已修正 谢谢
