### ISSUE TITLE
Error: Unknown section:MITHM

### ISSUE THREAD

**Issue by mgh2008** [lhie1/Surge#86]
surge1.2.6使用https://raw.githubusercontent.com/lhie1/Surge/master/Surge.conf报错，Error: Unknown section:MITHM

**Comment by lhie1** [comment]
不支持1.2.6版本

**Comment by mgh2008** [comment]
有没有1.2.6版本可用的？谢谢

**Comment by lhie1** [comment]
没有 不好意思
