### ISSUE TITLE
[iOS Surge] 最新的 Surge conf 会导致什么值得买app崩溃

### ISSUE THREAD

**Issue by kevinzfjiang** [lhie1/Surge#89]
估计有些reject规则引起，会导致app首页刷新数据就崩溃。只好user rule加了以下规则白名单。
USER-AGENT,smzdm*,direct
USER-AGENT,SMZDM*,direct

**Comment by lhie1** [comment]
总感觉会引起 app 闪退的问题不会是规则引起的 我还没来得及测试 晚一点我试试

**Comment by lhie1** [comment]
已修复
