### ISSUE TITLE
为什么前面skip-proxy跳过rule，后面rule里还要加IP段匹配？

### ISSUE THREAD

**Issue by lupin92** [lhie1/Surge#90]
skip-proxy = 127.0.0.1,192.168.0.0/16,193.168.0.0/24,10.0.0.0/8,172.16.0.0/12,100.64.0.0/10,localhost,*.local,e.crashlytics.com,captive.apple.com

IP-CIDR,10.0.0.0/8,DIRECT
IP-CIDR,100.64.0.0/10,DIRECT
IP-CIDR,127.0.0.0/8,DIRECT
IP-CIDR,172.16.0.0/12,DIRECT
IP-CIDR,192.168.0.0/16,DIRECT

**Comment by kevinzfjiang** [comment]
作者的faq里有解释。去掉ip-cidr段可能导致推送延迟。
这个google和作者的文档有说明。严格来讲不是issue

**Comment by lhie1** [comment]
好的 我还没注意过这方面的问题 谢谢指导

**Comment by lupin92** [comment]
@kevinzfjiang 

"IP-CIDR, 17.0.0.0/8, DIRECT, no-resolve
如果禁用此选项，可能会导致一些系统问题，例如推送通知的延迟。
注意：整个17.0.0.0/8地址块分配给苹果。“

这里说的去掉IP-CIDR段可能导致推送延迟，
指的是IP-CIDR, 17.0.0.0/8, DIRECT, no-resolve
因为17.0.0.0/8是苹果的域名
而苹果信息推送是通过自己服务器实现的。

**Comment by lhie1** [comment]
谢谢
