### ISSUE TITLE
爱奇艺两个问题，请验证。

### ISSUE THREAD

**Issue by sh3rry** [lhie1/Surge#91]
## DOMAIN-SUFFIX,paopao.iqiyi.com,REJECT   会导致"我的收藏“加载非常慢
![image](https://cloud.githubusercontent.com/assets/9400373/26272924/e7a4c978-3d56-11e7-9700-5eb0a5e77506.png)
![image](https://cloud.githubusercontent.com/assets/9400373/26272947/76617968-3d57-11e7-89ab-a9e7fa3c4014.png)

## IP-CIDR,101.227.200.0/24,REJECT,no-resolve  如下图，*有时*视频刚好分配到此段IP，会无法加载，等一段时间或者刷新几次又能播放，建议缩小IP范围。（图中是VIP剧集，测试到被阻挡的ip是101.227.200.113，可能还有其他的）
![image](https://cloud.githubusercontent.com/assets/9400373/26272937/48ea1e86-3d57-11e7-98d9-bf7e8840ee19.png)

**Comment by lhie1** [comment]
好的
