### ISSUE TITLE
FINAL规则的问题

### ISSUE THREAD

**Issue by sh3rry** [lhie1/Surge#93]
最近拿mac更新office和Adobe软件发现速度非常慢，从而发现的这个问题。

最后的 FINAL,☁️ Proxy 这条规则我认为非常不妥，应该改成FINAL,🔰 Proxy。和GEOIP,CN,🔰 Proxy 一样，用🔰 Proxy而不是☁️ Proxy。即在🔰 Proxy设为DIRECT时是FINAL,DIRECT。

这个条规则应该算比较明显的问题，不知道以前为什么没人提出。

在🔰 Proxy设为DIRECT时，FINAL,☁️ Proxy 这条规则加上前面的GEOIP,CN,🔰 Proxy  会导致只要是国外IP，最后都从代理走了（即使是不用翻墙的网站）。 黑名单白名单也变的没有意义了，因为黑名单里面的域名（google，youtube等等）都是国外IP，白名单（qq,微信等等）几乎都是国内的，直接GEOIP,CN,🔰 Proxy然后FINAL,☁️ Proxy就行了，还要黑白名单干什么啊对不对，这样浪费流量，也影响速度，而且也不能叫“智能分流“了。所以我觉的这个应该是个规则问题，不是作者的本意。

**Comment by lhie1** [comment]
不在名单上的国内ip直连 国外ip代理

不觉得有什么问题阿 根据自己的使用情况定制修改就可以了

Worklfow 可以自定义添加/删除

**Comment by sh3rry** [comment]
@lhie1 👌好的了解了 ，可能是需求不同，那我自己再定制下。
