### ISSUE TITLE
几处冲突与重复。

### ISSUE THREAD

**Issue by sh3rry** [lhie1/Surge#94]
DOMAIN-SUFFIX,crashlytics.com,🔰 Proxy
DOMAIN-SUFFIX,crashlytics.com,☁️ Proxy

DOMAIN-SUFFIX,piaotian.net,🔰 Proxy
DOMAIN-SUFFIX,piaotian.net,☁️ Proxy

DOMAIN-SUFFIX,rime.im,🔰 Proxy
DOMAIN-SUFFIX,rime.im,☁️ Proxy

DOMAIN-SUFFIX,twitch.tv,🔰 Proxy
DOMAIN-SUFFIX,twitch.tv,☁️ Proxy

DOMAIN-SUFFIX,playstation.com,🔰 Proxy
DOMAIN-SUFFIX,playstation.com,☁️ Proxy

DOMAIN-SUFFIX,playstation.net,🔰 Proxy
DOMAIN-SUFFIX,playstation.net,☁️ Proxy

DOMAIN-SUFFIX,playstationnetwork.com,🔰 Proxy
DOMAIN-SUFFIX,playstationnetwork.com,☁️ Proxy

DOMAIN-SUFFIX,sony.com,🔰 Proxy
DOMAIN-SUFFIX,sony.com,☁️ Proxy

DOMAIN-SUFFIX,sonyentertainmentnetwork.com,🔰 Proxy
DOMAIN-SUFFIX,sonyentertainmentnetwork.com,☁️ Proxy

DOMAIN-SUFFIX,mob.com,REJECT 
DOMAIN-SUFFIX,mob.com,🔰 Proxy

DOMAIN-SUFFIX,cn,🔰 Proxy
DOMAIN-SUFFIX,com.cn,🔰 Proxy（与cn重复）
DOMAIN-SUFFIX,edu.cn,🔰 Proxy （与cn重复）

DOMAIN-SUFFIX,googletagmanager.com, REJECT   
DOMAIN-SUFFIX,googletagmanager.com, REJECT (重复）

**Comment by lhie1** [comment]
已修改 谢谢
