### ISSUE TITLE
爱奇艺还有点问题

### ISSUE THREAD

**Issue by sh3rry** [lhie1/Surge#95]
还是有视频放不出来,然后看了一下，/22的屏蔽范围比上次修改之前的/24范围更大了啊。。
IP-CIDR,101.227.200.0/22,REJECT,no-resolve

![image](https://cloud.githubusercontent.com/assets/9400373/26709684/0caacdb4-4787-11e7-9298-ef87f32155f1.png)
![image](https://cloud.githubusercontent.com/assets/9400373/26709674/faaf2bbe-4786-11e7-8ad8-eba53b2bc4cf.png)
![image](https://cloud.githubusercontent.com/assets/9400373/26709655/e25b9bec-4786-11e7-8ca4-3a4e787e04eb.png)

**Comment by lhie1** [comment]
我说过 这条规则可以拦截大部分地区的广告 但也会导致小部分视频无法播放 必要的时候自行删除就好

暂时只能用这种办法去除爱奇艺广告

**Comment by sh3rry** [comment]
好的
