### ISSUE TITLE
FTChinese App 广告有没有办法破？

### ISSUE THREAD

**Issue by luzhaohui** [lhie1/Surge#98]
经常在手机上看 FTChinese ，广告太烦人了，有没有办法破？谢谢先

**Comment by lhie1** [comment]
客户端还是网页？

**Comment by luzhaohui** [comment]
是客戶端

**Comment by lhie1** [comment]
有时间会加上

**Comment by luzhaohui** [comment]
@lhie1 感谢并期待。网页看 FTChinese 还勉强过得去，毕竟有 Adguard 之类的，手机客户端上就无法忍受了，实在太多广告了。

**Comment by lhie1** [comment]
已屏蔽 更新规则后卸载重装即可

**Comment by luzhaohui** [comment]
@lhie1 实测，更新规则卸载重装后，启动广告已经屏蔽了，里面内嵌的广告还有。不过也已经很感谢了。

**Comment by lhie1** [comment]
![](http://i.imgur.com/pbZ6oZs.jpg)![](http://i.imgur.com/4yzK0VG.jpg)

**Comment by luzhaohui** [comment]
我這裡是這樣的



從我的 iPhone 傳送
